### ISSUE TITLE
Our People - Build Out Full Staff Directory

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1043]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/147194416406843)

**Comment by rossvanderlinde** [comment]
I need to figure out how that works with full width

**Comment by rossvanderlinde** [comment]
http://www.newamerica.org/central-staff/ as a model ?

**Comment by kjacks** [comment]
We need to figure out the structure of this as well - what is the default our people page?  Will it default to the staff directory or to the existing page

**Comment by rossvanderlinde** [comment]
+ use new page as staff directory page on the intranet

**Comment by rossvanderlinde** [comment]
➤ Ross van der Linde commented:
tagging https://app.asana.com/0/92711502709794/92711502709794 to confirm the additional fields necessary in wagtail to provide full functionality for intranet (I'm thinking phone, office number, office city (DC,NY,Chi,CA)
