### ISSUE TITLE
Content Grid Formatting

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1049]
Can we use this gray for all content grid categories and dates (per homepage carousel)
![screen shot 2016-06-23 at 12 12 10 pm](https://cloud.githubusercontent.com/assets/13524901/16310754/ce164146-393b-11e6-8747-ca3f501cc71d.png)

Rather than this one
![screen shot 2016-06-23 at 12 12 18 pm](https://cloud.githubusercontent.com/assets/13524901/16310756/d0cce9ee-393b-11e6-82c6-f018d4fcf98b.png)

Many thanks!

**Comment by kjacks** [comment]
Also move date line next to program

**Comment by kjacks** [comment]
@rossvanderlinde - In cases of events, where there is a date and a time, do we still want to combine them with the program line?

![screen shot 2016-06-23 at 1 07 52 pm](https://cloud.githubusercontent.com/assets/6720200/16312635/a6bf9dce-3943-11e6-930b-ec7fd76a0e6a.png)

**Comment by rossvanderlinde** [comment]
where does that even happen? since aren't all events in the special event
content grid

**Comment by kjacks** [comment]
@rossvanderlinde in the search results page

**Comment by rossvanderlinde** [comment]
Ah right. Could go either way on this -- either exclude entirely or add to
top line after date
