### ISSUE TITLE
Search button vs. auto update search results 

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#1051]
Need to ask web stakeholders if they would like the content grids to auto update when a program/initiative is selected in the dropdown or a date is chosen - instead of having to click the "Update Search" button to kick-off the filtering

**Comment by LomaxRx** [comment]
[in progress](https://github.com/newamericafoundation/newamerica-cms/tree/65a4cf3be451e0edd59ea8cd985c2f69067f1e54)... added a new method to `/search/views.py/` for to allow ajax requests for rendered HTML ... method mimics object returned by `get_context` ([this](https://github.com/newamericafoundation/newamerica-cms/blob/7d7c1e6a02d0b391032da5ed3a3661877eaa51f6/mysite/helpers.py#L47-L49)) ... my want to consider more substantial rewrite of search templates/rendering

currently need to add pagination back.

**Comment by LomaxRx** [comment]
apart of larger project to build more dynamic content.
