### ISSUE TITLE
Role of Interns on Site

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#1052]
Interns currently set as "Former Staff/Guest Author" role.
Need to ask web stakeholders: 
- Should interns be marked as program staff? 
- Is it fine if they show up on Program Our People pages? 
- Because of alphabetical ordering, they could be the first names on the page - is this fine?

**Comment by rossvanderlinde** [comment]
Always external authors, not on Our People pages
