### ISSUE TITLE
Iframe Processing to remove tableau navs

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1059]
- currently tableau iframe includes their top nav and other page elements, to remove, can add "&:showVizHome=no"  to tableau iframe src

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/149259837772375)

**Comment by LomaxRx** [comment]
[This filter](https://github.com/newamericafoundation/newamerica-cms/blob/34de9cb9b5155b813aeb0018380c6966170b136a/home/templatetags/utilities.py#L202-L214) would fix the issue for users, although the [tableau documentation](http://kb.tableau.com/articles/howto/embedding-tableau-public-views-in-iframes) suggest that parameter is **required** ... so this may be unnecessary
