### ISSUE TITLE
Investigate New Jobs Listing Service

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1072]
- investigate jobs services to present to TDM

**Comment by kjacks** [comment]
Talk with Brooke, etc.

**Comment by georgiamoon** [comment]
@rossvanderlinde -- can you post any needs that you get from TDM to this issue? thanks!

**Comment by georgiamoon** [comment]
- LinkedIn Talent Solutions: https://business.linkedin.com/talent-solutions/recruiter
- SmartRecruiters: https://www.smartrecruiters.com/
- Workday: http://www.workday.com/
- SilkRoad: http://www.silkroad.com/
- iCIMIS: https://www.icims.com/

Resources:
- https://www.crowdreviews.com/best-recruiting-software
- Salesforce? https://appexchange.salesforce.com/listingDetail?listingId=a0N300000016aa0EAA

**Comment by georgiamoon** [comment]
sticking with Jazz. closing.
