### ISSUE TITLE
Set Allowed Hosts for Site

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1076]
- Currently in mysite/settings allowed sites is set to *, which is a potential security risk because it would allow anyone to host our site - should change to na-staging.herokuapp and production/newamerica.org

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/152981350214784)

**Comment by nmorduch** [comment]
This is what needs changing, yeah? https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/settings/production.py#L19

Do we also change it in the dev settings? https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/settings/dev.py#L7

I'm referencing https://docs.djangoproject.com/en/2.2/ref/settings/#allowed-hosts and I'm sure could figure this out but I don't have time right now. How big a security risk is this?

**Comment by jckpn** [comment]
I'm sure someone more experienced than me could provide more insight into how big of a risk it is but I found a pretty good article about it here: https://www.divio.com/blog/django-allowed-hosts-explained/

Given that it just requires the site URL to be added in place of the *, I'll create a PR for this now.
