### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1078]
https://chrxr.com/adding-rss-feed-wagtail-site/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/153626775468471)

**Comment by rossvanderlinde** [comment]
Important RSS feed: events page.

**Comment by rossvanderlinde** [comment]
![screen shot 2016-10-05 at 11 53 43 am](https://cloud.githubusercontent.com/assets/13524901/19120880/7d34f34a-8af2-11e6-9718-90955e6a2b10.png)
Updated design

**Comment by LomaxRx** [comment]
current [url patterns](https://github.com/newamericafoundation/newamerica-cms/blob/17cedacfa30ac0906c5924d4c1841d602b931ed3/mysite/urls.py#L20-L25): 
**/feed/**: all content
**/feed/program/\<program-slug\>/**: all content for program
**/feed/subprogram/\<subprogram-slug\>/**: all content for subprogram
**/feed/author/\<author-slug\>/**: all content for author
**/feed/\<content-type\>/**: all content for content type (based on model name, e.g. `/feed/policypaper/`, see options [here](https://github.com/newamericafoundation/newamerica-cms/blob/17cedacfa30ac0906c5924d4c1841d602b931ed3/rss_feed/feeds.py), this is also used for events)
**/feed/\<content-type\>/\<program-slug\>/**: filter content by program (e.g `/feed/blogpost/asset-building/`)

i think these work well and cover most bases. if ya'll think so too, can move on to adding links to templates.
