### ISSUE TITLE
Blog posts onto Google News

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1080]
EdCentral and some other NA content used to appear on Google News. Not sure how easy it is to set this up again. @kjacks not asking you to do it but tagging you so you know about it

**Comment by kjacks** [comment]
@rossvanderlinde Interesting - it looks like these are their guidelines
https://support.google.com/news/publisher/answer/40787?hl=en#technical

**Comment by rossvanderlinde** [comment]
Thanks -- I'd forgotten what exactly the process was. It may actually be something we in comms can take care of then. Adding @mariaelkin and @tylerrichardett if they want to try setting this up

**Comment by rossvanderlinde** [comment]
@tylerrichardett @mariaelkin -- remind me what the outcome was here?

**Comment by LomaxRx** [comment]
handled by comms
