### ISSUE TITLE
In-Depth: Homepage

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1089]
![screen shot 2016-07-15 at 2 57 15 pm](https://cloud.githubusercontent.com/assets/13524901/16885477/bbea6516-4a9c-11e6-9c1b-e3b8fc609b40.png)

**Comment by rossvanderlinde** [comment]
Alternative
![screen shot 2016-07-18 at 1 37 00 pm](https://cloud.githubusercontent.com/assets/13524901/16924350/d5f4ddc2-4cec-11e6-937d-d21f445bad19.png)

**Comment by kjacks** [comment]
@rossvanderlinde - we should figure out whether we want this to order by most recent or be manually ordered, so as to center the content we want to emphasize

**Comment by kjacks** [comment]
ross - "Just got some feedback on homepage design, unanimous support for larger homepage block with centered text, but not quite as tall as in the preview"

**Comment by kjacks** [comment]
@rossvanderlinde I will need that turquoise image in the background when you get the chance

**Comment by rossvanderlinde** [comment]
![backimage](https://cloud.githubusercontent.com/assets/13524901/17117566/95623bee-528a-11e6-866d-aa499a0abee4.png)
Image subject to change but dimensions would still be the same

**Comment by kjacks** [comment]
@rossvanderlinde should I hold off on adding it then?

**Comment by rossvanderlinde** [comment]
I think you can add it- presumably changing a jpeg isn't difficult if
necessary?
