### ISSUE TITLE
Author title underscore

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1091]
![screen shot 2016-07-18 at 10 00 39 am](https://cloud.githubusercontent.com/assets/13524901/16917203/95f867a2-4cce-11e6-8a34-04188f0a3aa5.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/156494253651815)

**Comment by kjacks** [comment]
A proposal from @rossvanderlinde to add an underline to author names
