### ISSUE TITLE
Tags to categorize content

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#11]

**Comment by rossvanderlinde** [comment]
Adding to May post-launch so we can evaluate whether they are needed, particularly for stitching together issue pages and relevant content

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by sanajaved7** [comment]
Documentation on implementing tags: http://docs.wagtail.io/en/v1.5.2/reference/pages/model_recipes.html#tagging
