### ISSUE TITLE
First letters of headings that come immediately after images not behaving

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1101]
See "Misconception #3" here: http://www.newamerica.org/education-policy/edcentral/multilingualism-tool-closing-achievement-gaps/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/163836241665507)

**Comment by tylerrichardett** [comment]
Looks like something in here likely needs to be adjusted:
.post-body.with-dropcap>.block-paragraph~.block-paragraph:first-letter

**Comment by kjacks** [comment]
![screen shot 2016-10-17 at 4 12 04 pm](https://cloud.githubusercontent.com/assets/6720200/19453791/ad6c38ac-9484-11e6-9b5d-d6a3253041fc.png)

**Comment by kjacks** [comment]
dropcap on headings after images or other content blocks is buggy

**Comment by LomaxRx** [comment]
not sure why [these lines](https://github.com/newamericafoundation/newamerica-cms/blob/e868fce8ac4fc4c58492b57b9bd86745df53e3a1/mysite/assets/scss/components/_post-body.scss#L27-L38) are necessary. removing
