### ISSUE TITLE
Gifs don't play

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1102]
Not sure why these exist anywhere on our website, but they do: http://www.newamerica.org/education-policy/edcentral/eight-facts-babies/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/163836241735209)

**Comment by LomaxRx** [comment]
requires new dependency ([Wand](https://pypi.python.org/pypi/Wand)). should punt until after django 1.10 / wagtail 1.7 upgrades are deployed
["When Wand is installed, Wagtail will automatically start using it for resizing GIF files, and will continue to resize other images with Pillow."](http://docs.wagtail.io/en/v1.4.1/advanced_topics/images/animated_gifs.html)
