### ISSUE TITLE
Some hyperlinked text not turning green on hover

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1105]
e.g. "Far and Away" and "#FarandAway" here: http://www.newamerica.org/nyc/events/far-and-away/

**Comment by rossvanderlinde** [comment]
When you add bold/italics to an a tag it'll stop taking on that mouseover effect; should be pretty easy to fix.

**Comment by LomaxRx** [comment]
duplicate of #1109?
