### ISSUE TITLE
Redirecting from https://edcentral.org not happening

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1106]
When Google searching an EdCentral blog post, it sends you to https://
<img width="612" alt="screen shot 2016-08-04 at 10 37 40 am" src="https://cloud.githubusercontent.com/assets/17412375/17405943/81a0a710-5a2f-11e6-84f0-190d9d072f6d.png">

Which then does this:
<img width="741" alt="screen shot 2016-08-04 at 10 38 11 am" src="https://cloud.githubusercontent.com/assets/17412375/17405950/8ed672d4-5a2f-11e6-9f00-971af3cbc718.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/163858646059236)

**Comment by kjacks** [comment]
interesting, the http redirect does work for that page, but the https doesn't
