### ISSUE TITLE
Searching by date on blog pages may still not be working for some users

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1107]
Here:
<img width="789" alt="screen shot 2016-08-04 at 10 40 20 am" src="https://cloud.githubusercontent.com/assets/17412375/17406044/ddc5c8b8-5a2f-11e6-8f98-3b53bb8b7f5a.png">

Working fine for me though

**Comment by kjacks** [comment]
@tylerrichardett what was the issue here?  The ability to click the update search button?

**Comment by rossvanderlinde** [comment]
@tylerrichardett -- can you clarify the issue here. Was this feedback from someone?

**Comment by kjacks** [comment]
update from tyler: feedback from someone in ed that when clicking the update search button on chrome/windows the search results didnt update

**Comment by LomaxRx** [comment]
will be fixed with #1051
