### ISSUE TITLE
Fonts not loading on calendar

### ISSUE THREAD

**Issue by tylerrichardett** [newamericafoundation/newamerica-cms#1108]
Not sure what browser Laurel is using but she sent this:
![search function font 1](https://cloud.githubusercontent.com/assets/17412375/17406083/130de0be-5a30-11e6-8ea9-2feda5b648b8.PNG)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/163858645712036)

**Comment by kjacks** [comment]
This one is strange because it happens probably about 5-10% of the time, but shows the correct fonts the rest of time.  It almost surely has to do with loading wait time/order for those font files + the dependencies for the datepicker - I will investigate though
