### ISSUE TITLE
Link highlighting

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1109]
`a:not(.button):hover { background-color: #e0e0e1; padding-top: 3px; color: #2c2f35; }`
Used the approach Wired.com and others are taking to (hopefully) improve how links react to user mouseover
![screen shot 2016-08-08 at 2 08 44 pm](https://cloud.githubusercontent.com/assets/13524901/17490791/a0985e56-5d72-11e6-8b7c-08baec5966b4.png)

**Comment by kjacks** [comment]
proposed change to how links are highlighted on mouseover on the site from the current setup (where the text becomes turquoise) to a setup where the link changes background color on mouseover

**Comment by LomaxRx** [comment]
should be fixed in conjunction with #1105

**Comment by rossvanderlinde** [comment]
@LomaxRx this was an idea -- and possibly something we don't want to go ahead with. just fyi
