### ISSUE TITLE
"Seats Left" Event Alert

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1167]
Requires Cvent API integration + feedback from events

**Comment by kjacks** [comment]
This proposed feature would add a "Seats left" counter to event pages and perhaps to other places where events are advertised on the site.  The goal would be to increase event attendance.  Would require integration with the cvent API to get current signup numbers. 

Concerns: would events show up vastly underattended? Is this the kind of feel we want on our site?
