### ISSUE TITLE
Dropcap quotation marks

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1168]
![screen shot 2016-09-29 at 4 15 53 pm](https://cloud.githubusercontent.com/assets/13524901/18970657/1b2460e6-8660-11e6-90d7-51c34c70e0cc.png)

**Comment by LomaxRx** [comment]
is that the desired output or current output?

**Comment by kjacks** [comment]
@rossvanderlinde I'm not sure what the desired output would be here - on the one hand it looks strange to include the quotation mark in the dropcap, but there isn't really a way to exclude it if the article begins with a quote

**Comment by LomaxRx** [comment]
no good way to solve this. unless we want to change the way we do drop caps to wrapping the first character in a <span/> with some JS. not ideal IMO. closing for now.
