### ISSUE TITLE
RSS Feed - where to add link in content grids

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1175]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/189540209352899)

**Comment by rossvanderlinde** [comment]
Was thinking about this yesterday -- since we were going to move the social media icons to the bottom of the site, and we need to be able to link pretty much every page on the site to an RSS feed, what do you think of this solution? 

![screen shot 2016-10-26 at 9 37 42 am](https://cloud.githubusercontent.com/assets/13524901/19728048/f117ac9e-9b5f-11e6-8bc5-295ca0a49a6c.png)

**Comment by rossvanderlinde** [comment]
1. Accessing the page
* New section to bottom of org-wide subscription sidebar (title: "Stay in Touch" or "Stay Connected" or "Subscribe"; contents would be links to newsletter/subscription page and the RSS feed page)
* New section to bottom of program sidebar, with same content as above
* Possibly, RSS icon next to title on content grid, linking directly to relevant RSS page. (Ask for feedback from programs on whether that's desirable)

2. RSS feed page
* User could either select from dropdown list of author names or choose from list of content types, list of programs, or list of initiatives (would appear only once a program is selected). Click "Get RSS" feed to go to the RSS page.

**Comment by rossvanderlinde** [comment]
Decision taken at web stakeholder:

1. Add RSS to footer of entire site, and change the bottom right of the footer to have icons (incl. RSS icon). This would direct to www.newamerica.org/rss (i.e. a page on our site that allows the user to select from many RSS pages)

(![s]https://cloud.githubusercontent.com/assets/13524901/19728048/f117ac9e-9b5f-11e6-8bc5-295ca0a49a6c.png)

2. Do not add RSS links to program sidebars.

3. Add the RSS icon to the right of content type in content grids for podcasts and blog posts only. This would link directly to the RSS feeds for those pages.

![screen shot 2016-12-01 at 3 10 59 pm](https://cloud.githubusercontent.com/assets/13524901/20810628/6959b7b2-b7d8-11e6-8be0-da7658e5a007.png)

4. For the RSS directory page (www.newamerica.org/rss), allow user to select either 1. Author Name or 2. a combination of Content Type | Program | Initiative. Then a Go To Feed button takes user to feed.
