### ISSUE TITLE
In-Depth - PDF download link in project footer

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1181]
- add pdf download link to in depth project footer, will require additional field in in-depth project model to specify link target

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/195495050883883)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-12-01 at 2 58 24 pm](https://cloud.githubusercontent.com/assets/13524901/20810192/b3e7b966-b7d6-11e6-83d8-09b61758faa0.png)
@kjacks thoughts? It may need to go on the other side since I know the right side gets long with contents.
