### ISSUE TITLE
Google Maps API for Events address field

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#119]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625099188)

**Comment by rossvanderlinde** [comment]
Let's put this on the backburner

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
Google map embedded in event pages, based on event location

**Comment by LomaxRx** [comment]
does #984 handle this?

**Comment by LomaxRx** [comment]
will be handled by #984

**Comment by kjacks** [comment]
@LomaxRx this was a different feature - where a map would automatically be produced on the events page by the address given
