### ISSUE TITLE
CMS CSS Edits

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#120]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625096052)

**Comment by rossvanderlinde** [comment]
` .tab-nav a { background-color: #2a8e88; border-top: 0.3em solid #2a8e88; } 

Change all instances of #43b1b0 to #2ebcb3

And all instances of #399796 to #2a8e88

Body font to Simplon (all fonts seem to be controlled from body tag, which currently specifies Open Sans)



.nav-wrapper .inner { -webkit-box-shadow: rgba(0,0,0,.25)0 0 25px; box-shadow: rgba(0,0,0,.25)0 0 25px; z-index: 10000; background:white }



.nav-main .menu-item a { font-size: 1.1em; font-weight: normal; }



header { background-color: #2ebcb3 }

body { font-family: Simplon /* Needs to be installed */ }

.nav-main .menu-active { background: #2ebcb3; text-shadow: none; }

.nav-main .menu-active > a { border-left-color: #2a8e88; }

.nav-main .menu-item a { border-left: 8px solid transparent; }

.nav-main a:hover, .nav-main a:focus { outline: none; background-color: rgba(100, 100, 100, 0.15); color: #2c2f35; text-shadow: none; }

.nav-search input { background-color: #eaeaeb; color: #2c2f35; }

.logo img { width: 120px; } /* Used our gmail logo image */

.tab-nav.merged { background-color: #2ebcb3; }

.breadcrumb { padding-top: 0; background: #2a8e88; }

.object > h2 { background: #eaeaeb; } 

.object > h2:before, .object > h2 label:before { background-color: #2c2f35; }

.object.required > h2 label:after { color: #2c2f35; } 

h2 { font-family: simplon }
`

**Comment by rossvanderlinde** [comment]
![screen shot 2016-02-04 at 12 15 12 pm 1](https://cloud.githubusercontent.com/assets/13524901/13923501/45146c02-ef57-11e5-914c-99d9d6f8fe98.png)

**Comment by rossvanderlinde** [comment]
Relegated to July. Review in the summer when new features are added / the Wagtail feature that allows the full CMS to be styled is fixed to properly inherit default css styling

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
Styling suggestions to further customize the editing interface - currently the only customizations are here: https://github.com/newamericafoundation/newamerica-cms/tree/staging/mysite/templates/wagtailadmin and here: https://github.com/newamericafoundation/newamerica-cms/blob/staging/home/wagtail_hooks.py
