### ISSUE TITLE
Text wrapping of long words in Weekly sidebar

### ISSUE THREAD

**Issue by LomaxRx** [newamericafoundation/newamerica-cms#1205]
![image](https://cloud.githubusercontent.com/assets/2473869/19978341/ffef911e-a1cc-11e6-9b5d-96a2d882ede8.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/207046215613065)

**Comment by LomaxRx** [comment]
@rossvanderlinde any idea how we want to resolve this? Smaller text? Wider sidebar?

**Comment by rossvanderlinde** [comment]
To keep things simple I'd recommend reducing font size slightly

`.weekly__sidemenu__sibling-list__entry__text h1 {
    font-size: 0.96rem;
    line-height: 115%;
}`

We could look at a more comprehensive solution in the medium term
