### ISSUE TITLE
301 redirect from http to https

### ISSUE THREAD

**Issue by rschulman** [newamericafoundation/newamerica-cms#1218]
Can we please implement a permanent 301 redirect from the insecure version of our site to the https version? Since we already serve https there is no reason I can think of to continue serving the insecure pages. A simple 301 from any page at http to the same page at https is easy and will do the job.

In the future, once the 301 is implemented and stable, I would recommend also turning on HTTP Strict Transport Security to prevent man in the middle TLS stripping attacks.

@georgiamoon said that tagging @LomaxRx would be helpful, so there we go.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/224288552329661)

**Comment by rossvanderlinde** [comment]
Thanks @rschulman we'll get working on this.
