### ISSUE TITLE
Limit subprogram dropdown to children of parent program in CMS

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#123]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625099380)

**Comment by rossvanderlinde** [comment]
This may ultimately not be possible; backburner.

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by LomaxRx** [comment]
active discussion on solution to this [here](https://github.com/torchbox/wagtail/issues/882). will check back in a few months for progress.
