### ISSUE TITLE
Blockquotes on OTI section are using New America Teal

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/newamerica-cms#1231]
See here: http://www.newamerica.org/oti/about-us/

I don't have a personal issue with it, but it means that blockquotes aren't covered in the OTI sub-theme colors wise, so i wanted to flag it as a bug.

cc @sloane101

**Comment by kjacks** [comment]
@georgiamoon ooh - good catch!

**Comment by LomaxRx** [comment]
This is odd. [This line](https://github.com/newamericafoundation/newamerica-cms/blob/5cd946fde9f780e980a1694cf9f949f7461d2389/mysite/assets/scss/components/_post-body.scss#L48) should cover it...and it renders properly locally. But that style simply isn't showing up in production.
