### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#125]

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-16 at 10 50 00 am](https://cloud.githubusercontent.com/assets/13524901/13816475/f0487330-eb64-11e5-879c-7e3bce951122.png)

**Comment by rossvanderlinde** [comment]
@kjacks and @sanajaved7 -- I don't think search results ever has a sidebar, since it's not part of any section. Is that okay?

**Comment by sanajaved7** [comment]
@rossvanderlinde @kjacks That sounds right to me since this is the general search results page and it's not housed under a program.

**Comment by rossvanderlinde** [comment]
@kjacks search page updated with new page number approach

![screen shot 2016-03-28 at 4 50 16 pm](https://cloud.githubusercontent.com/assets/13524901/14089868/38da313e-f505-11e5-8a10-2a529fcf4d95.png)

**Comment by rossvanderlinde** [comment]
- Search button here would by default have search text that was entered. Re-searching would just generate a new page.
- Dropdowns would stack onto two lines as page got thinner

**Comment by rossvanderlinde** [comment]
@kjacks how's this?
![screen shot 2016-03-29 at 12 08 39 pm](https://cloud.githubusercontent.com/assets/13524901/14114983/3b83ba8e-f5a7-11e5-9e4c-843c1cd3fffa.png)

**Comment by kjacks** [comment]
Looks great!

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-29 at 4 30 08 pm](https://cloud.githubusercontent.com/assets/13524901/14122868/916b938a-f5cb-11e5-9943-82f9e54cb840.png)
