### ISSUE TITLE
HTTPS redirects broken?

### ISSUE THREAD

**Issue by rschulman** [newamericafoundation/newamerica-cms#1267]
https://newamerica.org/oti/ is not redirecting to https://www.newamerica.org/oti/ right now. I'm getting a timeout error in Chrome.

**Comment by LomaxRx** [comment]
This is a lot more involved than I anticipated.

I think we have the simple s3 redirect setup for our "naked" domain, [outlined by Heroku](https://devcenter.heroku.com/articles/route-53#naked-root-domain) (right, @kjacks?) which says:

> S3 won’t allow you to configure an SSL certificate, so you cannot easily use Route 53 to redirect your root domain in HTTPS. If you need to do this, consider using a DNS provider that offers CNAME/ALIAS records root domains. For more information see the Custom domains Dev Center article, or this blog post, which shows how to set up a SSL naked domain redirect.

Looks like we're going to have to switch to a [cloudfront distribution](https://simonecarletti.com/blog/2016/08/redirect-domain-https-amazon-cloudfront/#configuring-the-amazon-cloudfront-https-redirect) to allow SSL requests to the naked domain

@natmey @georgiamoon @rschulman if you have any experience with this, let me know if this sounds right to you.
