### ISSUE TITLE
Post Pages - Anchor Routing Bug

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1281]
@LomaxRx this is a little bit difficult to explain without demonstration, but if you are on a post page, then scroll down, then hit the back button, you end up having to click back two or three times to leave the page.  

It seems that as you scroll it is adding an empty anchor (#) to the url, I'm guessing in conjunction with the new panels for post pages, which then adds an extra step to the back routing.

**Comment by LomaxRx** [comment]
bah! ok. thanks
