### ISSUE TITLE
Reroute users after first logging into CMS

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#129]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625163956)

**Comment by kjacks** [comment]
It's been noted that the initial home screen a user gets after signing into wagtail is really not that helpful (who really needs to know how many pages have been published in total on the site, etc) and that it would be more helpful to redirect users to the new america level editing page in the heirarchy (http://www.newamerica.org/admin/pages/3/).

Implementation for this feature is probably pretty complex though and is doubtful that it worth the time to implement
