### ISSUE TITLE
Creating redirects for an initiative that is changing its name

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1366]
@kevinhowbrook: This initiative: https://www.newamerica.org/education-policy/learning-technologies-project/ is going to be changing its name to "Teaching, Learning, and Tech" in May. We can change the slug on the website to "teaching-learning-and-tech", but that will change all child page URLs, and break hyperlinks. Possible to write a script to create redirects from all /learning-technologies-project pages to the new /teaching-learning-and-tech URL?

We haven't gotten the all-clear to do this yet -- the launch is probably May 6 at earliest. Just wanted to give a heads up.

**Comment by kevinhowbrook** [comment]
Hi @mariaelkin, thanks for the heads up. It is possible to write a script to create redirects, although I think the same could be achieved by changing the child page slugs and adding redirects for them via the wagtail UI at https://www.newamerica.org/admin/redirects/. I'm suggesting this as I noticed only 3 child pages in this section, but maybe I'm missing something?

**Comment by mariaelkin** [comment]
Sorry, you're right! I thought there were way more than just three child pages in that section. This is closed.
