### ISSUE TITLE
Audit of Heroku hosting costs

### ISSUE THREAD

**Issue by Floreat100** [newamericafoundation/newamerica-cms#1373]
Requested by Maria on Slack in April.

@kevinhowbrook will spend one hour looking into this.

**Comment by kevinhowbrook** [comment]
@lomaxap, I'd like to get more of a specific figure on the memory consumption of:
- Generating PDFs
- Parsing uploaded word docs
Is this something you have already obtained? If not it's a case of checking the Heroku performance logs when the events occur, just thought I would check first.

Thanks

**Comment by kevinhowbrook** [comment]
Audit document has been shared over slack with Maria
