### ISSUE TITLE
[1hr] Add Fabric task to pull staging database for Vagrant

### ISSUE THREAD

**Issue by kevinhowbrook** [newamericafoundation/newamerica-cms#1374]
The fixture.json contains values for fields that have since been removed, we are able to export stage databases to set up locally but it would be worthwhile to provide some new up to date fixtures and include them in the repo.

**This will make it easier for developers to set up the site locally**

Once complete, update the README and remove the database option instructions.

**Comment by nmorduch** [comment]
Currently not sure we want to do this.

**Comment by nmorduch** [comment]
Changing this ticket to be not fixtures but instead fabric/vagrant
