### ISSUE TITLE
Header - About Dropdown

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#138]
- update styling of about dropdown to align with button

**Comment by rossvanderlinde** [comment]
Content can be hardcoded (rather than dynamic). Should include:
- Our Story
- Our People
- Press
- Jobs
- Funders*
- Councils*

* Possible - to be confirmed

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-01 at 1 44 54 pm](https://cloud.githubusercontent.com/assets/13524901/13438193/f60ad5e8-dfb5-11e5-9f0d-b687578d5085.png)
