### ISSUE TITLE
Header - Programs Dropdown

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#139]
- Change layout of program dropdown to incorporate "New America Streams"
- waiting for specifics of how it ideally should be organized

**Comment by rossvanderlinde** [comment]
Right column should have two rows:
- Locations
-- New America DC
-- New America NYC
-- New America CA
-- New America Chicago
- Channels
-- New America Weekly
-- Context (Medium)
-- Icons for Twitter, Facebook, YouTube, LinkedIn, and (possibly) Google+

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-02 at 9 29 28 am](https://cloud.githubusercontent.com/assets/13524901/13463266/774af284-e059-11e5-8a97-b840e733bb52.png)

**Comment by rossvanderlinde** [comment]
<div class="small-12 large-12 columns">
                                            <h1 class="header__link-group__heading">Locations</h1>
                                            <a class="header__link-group__main-element" href="/better-life-lab/">New America DC</a><a class="header__link-group__main-element" href="/better-life-lab/">New America NYC</a><a class="header__link-group__main-element" href="/better-life-lab/">New America CA</a><a class="header__link-group__main-element" href="/better-life-lab/">New America Chicago</a><h1 class="header__link-group__heading" style="padding-top:50px">Channels</h1><a class="header__link-group__main-element" href="/better-life-lab/">New America Weekly</a><a class="header__link-group__main-element" href="/better-life-lab/">Context</a><a class="header__link-group__main-element" href="/better-life-lab/">Row of Icons Goes Here</a>
                                        </div>
