### ISSUE TITLE
[2-3hrs] Remove or hide option to copy (duplicate) pages

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1395]
@mariaelkin:
>Users will duplicate pages rather than making new child pages, which leads to errors. Rather than trying to fix it, I think we should hide the "copy" option from non-admin accounts or all accounts

**Comment by kevinhowbrook** [comment]
Hi @nmorduch,

I think there are 2 parts to this. The main task would be to ensure only admin/superusers can use the copy functionality. We should do this using the [`before_copy_page`](http://docs.wagtail.io/en/v2.2/reference/hooks.html#before-copy-page) hook and checking the group the user belongs to.

The second part would be the extension of hiding the button. This would require some discovery time but from some initial investigation, we could override [`register_page_listing_more_buttons`](https://github.com/wagtail/wagtail/blob/9be694b508b1dedb2616516fcd630727c0cd762e/wagtail/admin/wagtail_hooks.py#L155) or possibly just do the hiding with a css patch

I think it's best to allow around 2 to 3 hours for this task,

Thanks
