### ISSUE TITLE
Checkbox on subscribe page should default to checked

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1396]
https://www.newamerica.org/subscribe/

**Comment by kevinhowbrook** [comment]
Look like we just need to know what checkboxes need to be the default for this, setting them as default can be configured in the UI by editing the subscribe page:

![subsribe checkbox example](https://i.imgur.com/N6gy9ed.png)

**Comment by nmorduch** [comment]
Thanks, @kevinhowbrook :)

**Comment by nmorduch** [comment]
@kevinhowbrook two things:

- i checked the boxes on the main subscribe page and it didn't actually make a difference
- we also want to do this for the program subscribe pages, where the option isn't available (e.g. [newamerica.org/better-life-lab/subscribe](https://www.newamerica.org/better-life-lab/subscribe) / [newamerica.org/admin/pages/14/edit/#tab-promote](https://newamerica.org/admin/pages/14/edit/#tab-promote))

**Comment by victoriachan** [comment]
Hi,

This isn't straightforward. The 'checked by default' option on the subscribe page CMS comes from the `SubscribePage` model `newsletter_subscriptions` streamfield field (https://github.com/newamericafoundation/newamerica-cms/blob/master/home/models.py#L433).

The React frontend here https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/assets/react/program-page/components/Subscribe.js (I think) is responsible for displaying the checkbox as checked or not. It probably just assumes the checkboxes all start out as unchecked. 

I can't find where in the API it is getting the subscription list from. We might need to forward this to a more experienced React developer.

I'll let Paul know to sort out the resourcing.

Regards,
Victoria

**Comment by AnnaGrieve** [comment]
Need to assign a dev with React skills to look into this one

**Comment by kaedroho** [comment]
It looks like we get a list of `subscriptions` passed in props. According to the code, each item in this list has a `title` field so I'm assuming this also contains `checked_by_default` as well.

If that's the case, we should be able to add some code into the constructor that initialises `state.subscriptions` with the subscriptions that have this field set to True.

I think this would take an hour.

**Comment by AnnaGrieve** [comment]
To schedule in Dec support sprint

**Comment by AnnaGrieve** [comment]
I have upped the dev estimate on this one slightly given that it is React based

**Comment by kaedroho** [comment]
This is probably going to be more work than I initially thought. The values on the page are not used anywhere on the site, those checkboxes are actually taken from the `home_subscriptions` and `programs` keys in the `meta` API: https://github.com/newamericafoundation/newamerica-cms/blob/staging/newamericadotorg/api/meta/views.py#L38

This might require rewriting a fair bit of React code to make them use the field defined on the page model.

**Comment by nmorduch** [comment]
We want to wait on this one until we decide whether we're replacing campaign monitor

**Comment by nmorduch** [comment]
Will likely switch to talking to Salesforce, which will probably be a larger project to make sure that we don't accidentally mess up lists in salesforce
