### ISSUE TITLE
[1hr] Show sponsor logo on report page

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1398]
Reports can have a sponsor logo image, which currently is displayed only in the pdf. We'd like to display it at the bottom of the "Acknowledgements" section on report abstract pages.

e.g., on [this page](https://www.newamerica.org/oti/reports/centering-civil-rights-privacy-debate/), right before the footer, it would go here:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/1051450/63284887-97cf6800-c282-11e9-9ad8-d90596488596.png">

**Comment by kevinhowbrook** [comment]
Hi @nmorduch,

For this it looks like we just need to expose the partner logo on the api and configure it to display with react https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/api/report/serializers.py#L31 as it looks like entire reports page is using react. I'll request someone more knowledgable about react have a look into this but I would estimate this to be around 1 hour

**Comment by AnnaGrieve** [comment]
Need a developer with React skills to look into this one
