### ISSUE TITLE
[<1hr] Scale down open graph images

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1399]
Twitter often doesn't show image previews for reports. I believe the cause of this is that we're using the original images for open graph images. Twitter supports "minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size." ([source](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary))

For what to scale them to, I think this (found via a quick search) is a pretty good survey of the existing recommendations: https://iamturns.com/open-graph-image-size/

I'm inclined to do: if `(width / height) > 1.45` use `fill-1200x630`, otherwise use `fill-1200x1200`. Since 1200x630 is a ratio of about ~1.9:1, this puts the cutoff halfway between that and square.

**Comment by mariaelkin** [comment]
I would say this is a high priority fix for torchbox.

**Comment by kevinhowbrook** [comment]
Thanks for the information @nmorduch 

Looks like this is a case of correcting the [`base.html`](https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/templates/base.html#L36) to use an image tag with the correct size

E.g:

```
{% if page.story_image  %}
    {% image page.story_image width-320 as story_image %}
     <meta name="twitter:image" content="{{ story_image.url }}">
{% else %}
...
```

I would estimate this up to an hours work

**Comment by victoriachan** [comment]
Hi Naomi,

It isn't straightforward to do math operations on the template. We normally use `width-320` for the open graph images. Do you want me to use this or an alternative resize rule that doesn't require math operations?

Regards,
Victoria

**Comment by nmorduch** [comment]
Oh right. Let's go with `fill-1200x630` and I'll add some math someday when I have free time.

**Comment by victoriachan** [comment]
Hi Naomi, 

I've created an PR for this now: https://github.com/newamericafoundation/newamerica-cms/pull/1404 If you're happy with that I can put it on staging for testing. Though you probably wouldn't be able to test on Twitter Card validator etc if the site requires http authentication.

Regards,
Victoria

**Comment by nmorduch** [comment]
Merged but putting in `In review` because I want to deploy to and test in production before closing.

**Comment by nmorduch** [comment]
Deployed, and this appears to be fixed!
