### ISSUE TITLE
[0.5hr] Stage site should be protected

### ISSUE THREAD

**Issue by kevinhowbrook** [newamericafoundation/newamerica-cms#1400]
Capturing this issue here...

Making the stage site protected is rather straightforward. We usually implement this via HTTP basic access authentication, it's a minimal task, maximum of about .5h 

@nmorduch  Would you want us to whitelist any specific IPs?

Thanks

**Comment by nmorduch** [comment]
Good plan. I'm looking to which IPs

**Comment by nmorduch** [comment]
Sent in Slack!

**Comment by AnnaGrieve** [comment]
Karl to pick this up together with stage site rebuild
