### ISSUE TITLE
New newsletter segment not showing in the NA-wide subscribe page

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1402]
The script we ran to make a new newsletter subscription segment show up on the website worked insofar as the new segment appears on the program's page https://www.newamerica.org/better-life-lab/subscribe but the new segment does not show up among the program lists in the org-wide subscribe page: https://www.newamerica.org/subscribe

I don't believe there's anything else our team has had to do in the past to make it show up org-wide; can you look into it?

**Comment by nmorduch** [comment]
They're not manually added here? https://www.newamerica.org/admin/pages/7597/edit/

**Comment by nmorduch** [comment]
LuLin says that didn't work. Taking a look now.

**Comment by nmorduch** [comment]
I think it was just caching again.
