### ISSUE TITLE
Mobile Header - Incorporate Drilldown/Accordion

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#141]
- Mobile Header Design and Implementation

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-03 at 12 00 52 pm](https://cloud.githubusercontent.com/assets/13524901/13502349/a00a179c-e138-11e5-9a13-d2d258d88db8.png)

**Comment by rossvanderlinde** [comment]
In case it helps, here's some code for neatly flipping the arrow http://codepen.io/anon/pen/oxXOJg
