### ISSUE TITLE
[2-3hrs] Subpages of private reports are accessible

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1416]
From @mariaelkin in https://github.com/newamericafoundation/newamerica-cms/issues/1403#issuecomment-539159642
>In reports, if you publish a report that is password-protected, only the landing page prompts a password. If someone has a direct link to one of the interior page of the report, they can access it without putting in a password.

I think this is likely caused by the way urls are handled (which I believe is an attempt to keep Django urls and React router from stepping on each other's toes). e.g. https://github.com/newamericafoundation/newamerica-cms/blob/staging/newamericadotorg/urls.py#L54

**Comment by nmorduch** [comment]
Basically..... sections of reports not being Pages causes various interesting side effects and problems. An interesting thing that will probbbbbbbably never cause a problem is that the program name doesn't actually matter at all in the url for a section of a report, e.g.:

https://www.newamerica.org/abcdef/reports/apprenticeship-review/higher-education-community-colleges-and-degree-apprenticeship/

So if two different programs ever had reports with the same name, with sections with the same name.... it doesn't seem like a high priority thing to test it out it to see what would happen.

**Comment by nmorduch** [comment]
Another one is that you can't add redirects from things that are sections of programs. Which is more annoying as we're working on #1422

**Comment by nmorduch** [comment]
There must be a better way to handle this url situation. Do we make it so that sections of reports have Pages in Wagtail? I expect there would be a number of complicated things about that plan. Can/should we change to a hash router for the React sections of the site? Some other less-buggy way to have React handle some-but-not-all of the urls?

**Comment by kaedroho** [comment]
If I've understood this correctly, I think we could solve this by using [RoutablePageMixin](http://docs.wagtail.io/en/v2.1.1/reference/contrib/routablepage.html) on the `Report` page type to make it also respond on URLs directly beneath it. This would mean that Wagtail's routing would be used to find the `Report` page so it can check if it is password protected and this would also mean that the previous components in the path would be checked too.

Does that sound right?

**Comment by AnnaGrieve** [comment]
Hi @nmorduch - we reckon this would require about 2-3 hours effort to implement, just checking you can confirm Karl's comments above?

**Comment by nmorduch** [comment]
At a quick glance, that makes sense!
