### ISSUE TITLE
Draft pages are visible in some parts of the site

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1417]
The problem appears to be that when a page should not appear, whether that's because it's a draft or private or both, it can still show up on other pages that use React to grab a list of other pages. I'm guessing that this is an API setup problem.

- [x] Draft report showing up in a public RSS feed (#1403)
- [x] Draft edition of The Weekly showing up at [newamerica.org/weekly](https://newamerica.org/weekly)

**Comment by AnnaGrieve** [comment]
Assigning to @jacobtoppm

**Comment by jacobtoppm** [comment]
I've submitted a PR for review here: https://github.com/newamericafoundation/newamerica-cms/pull/1423

This should address the issue: Weekly queries were missing a `.live().public()` and Feed queries a `.public()`. 

I haven't changed how the latest edition is selected, aside from making it reject draft or private versions, as I didn't want to break any behaviour you're relying on. However, I've noticed that it doesn't have any ordering actually set in the query. While Wagtail's default ordering should grab the latest edition most of the time assuming you're adding them sequentially, this could potentially lead to problems if you update or re-publish an existing edition. Let me know if you would like me to add an ordering for you - either by the publication date or the edition number in the title.

**Comment by nmorduch** [comment]
Thank you!

Let's make the ordering a separate ticket, since it's lower priority and I'd like to get this fix in sooner.

**Comment by AnnaGrieve** [comment]
Assigning to @kaedroho to review PR

**Comment by nmorduch** [comment]
Currently testing on staging!

**Comment by nmorduch** [comment]
Looks good on staging!

**Comment by nmorduch** [comment]
Closed with #1429
