### ISSUE TITLE
Report is generating a PDF of 0kb size

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1421]
This PDF is the culprit: https://www.newamerica.org/admin/pages/24570/edit/

The steps I follow to generate the PDF are:
1. Go to the PDF publishing tab
2. Check the "Generate PDF on Save" box
3. Click Save Draft
4. Wait 5-10 seconds, refresh the page, go back to "PDF Publishing." What's supposed to happen is the checkbox would be unchecked once more, the newly generated PDF would be there, and you'd click Publish to push it to the website.

However, in this case, the box remains checked and no new PDF appears. When I go to the Documents section of Wagtail, each attempt I made to generate the PDF is there, but the files are all 0kb https://www.newamerica.org/admin/documents/

One possible culprit could be that the size of the PDF is making it difficult to generate -- this one has many embedded images and the last functioning PDF that was generated was 12mb.

This is an urgent priority, as the report has already launched and been made public today, but there's no option to download it.

**Comment by AnnaGrieve** [comment]
We'll take a look. Likely to be related to #1408, #1419

**Comment by AnnaGrieve** [comment]
From @kaedroho  - just looking at this now. Looks like Gunicorn (the web server that hosts the new PDF generator) has been timing out. The google cloud run timeout is 10 minutes but I didn't realise gunicorn enforces its own timeout of 30 seconds. I will increase this to 10 minutes as well now

This change has now been made, could you try it again? (I haven't got a login)
