### ISSUE TITLE
[1hr] Create redirects for program name change

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-cms#1422]
This program www.newamerica.org/bretton-woods-ii/ is going to be changing its name soon and rather than migrate their content to an entirely new program page, we'd like to change their URL to www.newamerica.org/digi. As a result, all links with /bretton-woods-ii will need to be redirected /digi.

I'm waiting on the official word on the timeline, but the deadline when they will debut the new name is likely going to be 11/13.

Is it possible to estimate your timeline for this?

**Comment by nmorduch** [comment]
Update: deadline is indeed the 13th.

**Comment by AnnaGrieve** [comment]
Need to confirm if we can do this for the 13th.

**Comment by AnnaGrieve** [comment]
Assigning to Karl to confirm

**Comment by AnnaGrieve** [comment]
Karl thinks we can script this if there are a lot of them (assuming it applies to page tree) - this would be ~ 1 hour effort.
