### ISSUE TITLE
[2.5 hrs] Add breadcrumb to search results | BE

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1427]
Split from #1414, especially https://github.com/newamericafoundation/newamerica-cms/issues/1414#issuecomment-546925768

@kaedroho's estimate: 1.5 hours backend. 1 hour React

@kaedroho to pass to @nmorduch for styling when the breadcrumbs exist (unless there are already breadcrumbs somewhere on the site such that it's trivial)

**Comment by AnnaGrieve** [comment]
With @nmorduch to review

**Comment by nmorduch** [comment]
Closing because covered by #1485
