### ISSUE TITLE
Content Page - Hero, Title, Breadcrumbs

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#144]
Design 1

![screen shot 2016-03-01 at 12 56 32 pm](https://cloud.githubusercontent.com/assets/13524901/13436423/3014e6ce-dfad-11e5-9394-d5da9ed9c8a9.png)

Design 2

![screen shot 2016-03-01 at 1 01 21 pm](https://cloud.githubusercontent.com/assets/13524901/13436543/be7dbeb8-dfad-11e5-9352-f97f0486fcac.png)

I think I prefer the second.

**Comment by rossvanderlinde** [comment]
With excerpt
![screen shot 2016-03-01 at 1 07 01 pm](https://cloud.githubusercontent.com/assets/13524901/13436696/88c95cb8-dfae-11e5-8120-60bb9aebfa3f.png)

**Comment by rossvanderlinde** [comment]
Let's go ahead with design 2.

**Comment by kjacks** [comment]
This issue has been resolved by new content page redesign - Issue #161
