### ISSUE TITLE
[<1hr] Set up Hirefire

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1445]
https://www.hirefire.io/

**Comment by AnnaGrieve** [comment]
Hi @nmorduch - to follow up on this, I've logged a ticket with our Sys Admin team to book some resource time for this one.

**Comment by AnnaGrieve** [comment]
Hi @nmorduch - a further update - I'm waiting to confirm when our Sys Admin team can schedule this in, but I'm confident it will be before Christmas - just need to confirm exactly when.

**Comment by AnnaGrieve** [comment]
Hi @nmorduch - unfortunately due to the Django security issue before Christmas we didn't get to this one - I'm now hoping it will be scheduled in towards the end of January - I will keep you posted.
