### ISSUE TITLE
Program Landing Page Basic Design

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#145]
- Adapt Grid from Home Page with new breakpoints
- fix styling/ text overflows
- featured stories square images
- About Panel not to extend full-width like our story

**Comment by rossvanderlinde** [comment]
![blogdesign-programlanding](https://cloud.githubusercontent.com/assets/13524901/13500817/2ed13d22-e132-11e5-8d15-74c16ad92a92.png)
