### ISSUE TITLE
[5 hrs] Stop having editions in The Weekly | BE

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1455]
The Weekly is going to stop having editions and start posting things as they're ready. This obviates #1424. I think we'll want to use edition pages ([Edition.js](https://github.com/newamericafoundation/newamerica-cms/blob/staging/newamericadotorg/assets/react/weekly/components/Edition.js)) as the base for the new Weekly homepage.

I can definitely do the design changes, and am less confident when it comes to changing React/Python parts. Torchbox (probably @kaedroho), can you look at this plan and see if you think it makes sense?

- [x] Backend work (Tbx)
  - [x] Update the Weekly API so that it returns all articles rather than editions [weekly/serializers.py](https://github.com/newamericafoundation/newamerica-cms/blob/staging/newamericadotorg/api/weekly/serializers.py)
  - [x] Add pagination (ie the "load more" button)
  - [x] Move article pages all to be children of the weekly homepage and make redirects.
  - [x] [/weekly](https://www.newamerica.org/weekly) should point to the Weekly homepage, not to editions

FE (Naomi) split to #1486
- New Weekly homepage design
  - Like an edition page, including keeping a full-width article at the top
  - Move subscription CTA to a card (like on program homepages), put it in the second row. Maybe the first card in the second row. Or maybe 2 cols wide?
  - Add date to article cards
  - Probably remove black bar entirely
  - Add pagination (ie the "load more" button)
- Weekly article design
  - Black bar at the top should link back to the Weekly homepage, not to an edition
  - Take away the text that says "Weekly Article" under the headline

**Comment by AnnaGrieve** [comment]
@kaedroho to take a look today

**Comment by kaedroho** [comment]
This sounds good to me! Just a couple of comments:

We would also need to update the Weekly API so that it returns all articles rather than editions
Do we need to provide redirects for past editions? It might be difficult to support this if the pages have to be restructured.

**Comment by nmorduch** [comment]
Would the redirects be easy if we use [that thing you wrote for making redirects from pages to themselves](https://github.com/newamericafoundation/newamerica-cms/blob/staging/home/management/commands/pregenerate_redirects.py)?

Will add the bit about the API. And then can you estimate the BE work?

**Comment by kaedroho** [comment]
> Would the redirects be easy if we use that thing you wrote for making redirects from pages to themselves?

Yep, that would work for the articles, is it possible that we would need to add redirects for the edition pages as well? (If so, where would these requests go? Will we allow filtering historical articles by edition?)

Estimates on those points:

>  Update the Weekly API so that it returns all articles rather than editions weekly/serializers.py

2.5 hours

> Add pagination (ie the "load more" button)

1 hour

> Move article pages all to be children of the weekly homepage and make redirects.

To write a script that moves these pages, adds redirects, and deletes edition pages. 1.5 hours

>  /weekly should point to the Weekly homepage, not to editions

Looks like this redirect is set up in [React](https://github.com/newamericafoundation/newamerica-cms/blob/830f28d3d45a3d8fe4eb4473cc1aa98a3c47b202/newamericadotorg/assets/react/weekly/index.js#L99-L101). Only backend code around rendering the weekly homepage I could see was some [custom logic for previews](https://github.com/newamericafoundation/newamerica-cms/blob/staging/weekly/models.py#L23-L25), I'm not sure why this exists though.

**Comment by AnnaGrieve** [comment]
Karl has estimated 5hrs in total see above.

**Comment by nmorduch** [comment]
re redirects for edition pages, I think we should just not make them tbh. Maybe let's print a list of articles and what editions they go to, when doing this, just so we have that historical information? I'm going to check in with the person in charge of the Weekly about this, though.

**Comment by nmorduch** [comment]
Call it 3 hrs for my part

**Comment by nmorduch** [comment]
We can dump the editions entirely, no need to retain a memory of what they were. Old edition pages can redirect to the weekly homepage.

**Comment by kaedroho** [comment]
Backend tasks implemented in https://github.com/newamericafoundation/newamerica-cms/pull/1493
