### ISSUE TITLE
Emergency upgrade to Django 2.2.9

### ISSUE THREAD

**Issue by jckpn** [newamericafoundation/newamerica-cms#1457]
We already have this noted as a high priority internally -- thought it was worth copying here too: 

Django version 3.0.1/2.2.9/1.11.27 is expected to release Wednesday 18th (tomorrow) at 12:00 UTC, patching a high severity security defect. Given the nature of this update it will most likely need to be applied ASAP.

> Django versions 3.0.1, 2.2.9 and 1.11.27 will be released on
> Wednesday, December 17, 2019 around 1200 UTC.
> They will fix a security defect with severity “high”.

**Comment by nmorduch** [comment]
Closed with 6f610293f1fe9c5617e7c307bead556b97094d49 which updated to Django 1.11.27
