### ISSUE TITLE
[1hr investigation] Preview isn't working in admin for any pages

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1482]
Used to be just the ones that used React. Haven't confirmed

**Comment by AnnaGrieve** [comment]
Investigate why non-React pages don't work in preview is priority

**Comment by AnnaGrieve** [comment]
@nmorduch to provide example

**Comment by nmorduch** [comment]
It apparently used to work for things like simple pages or about pages or whatever they’re called, and event pages, and missy pages really, just not things like report pages and homepages (so don’t worry about those)

**Comment by kaedroho** [comment]
This issue existed on staging. Appears to have been the site record being set incorrectly to `localhost`. Changing it to the correct domain name fixed preview.

Could you check on production? (in Wagtail => Settings => Sites)
