### ISSUE TITLE
[4hr] Add time zone to events

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1517]
With online events, it's not immediately clear that they're in different time zones when they're hosted by different locations

**Comment by jacobtoppm** [comment]
When you enter times in the Wagtail Admin, the default assumption is that it's in the user preferred timezone (or the server timezone, if not set). Did you want to allow the user to set this in an arbitrary timezone, and then display this on the event page? With your current setup, it looks like you'd just get it in the server/user time.

**Comment by nmorduch** [comment]
Yeah, I think that while sitting in Eastern Time we should be able to create an event that takes place at 3:00 Pacific Time, and have it display as 3:00 Pacific Time.

**Comment by jacobtoppm** [comment]
Because we need to work around the existing timezone override on this one, I anticipate this could be a little fiddly, so I'd estimate around 4 hours.

**Comment by chigby** [comment]
@nmorduch Curious how you envision the UI here from the admin point of view. Something like a drop-down list with time zones on it? Just US time zones? Or something else?
