### ISSUE TITLE
Home Page - Lead Stories Image (Styling and Behavior on Mouseover)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#152]

**Comment by rossvanderlinde** [comment]
.hero-grid__element__background:before { background: -moz-linear-gradient(center top , rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0) 1%, rgba(0, 0, 0, 0.06) 16%, rgba(0, 0, 0, 0.4) 75%, rgba(0, 0, 0, 0.6) 100%) repeat scroll 0 0 rgba(0, 0, 0, 0); background: -webkit-linear-gradient(top , rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0) 1%, rgba(0, 0, 0, 0.06) 16%, rgba(0, 0, 0, 0.4) 75%, rgba(0, 0, 0, 0.6) 100%); bottom: 0; content: " "; display: block; height: 50%; left: 0; position: absolute; transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1) 0s; width: 100%; opacity: 1; z-index: 1; }

**Comment by rossvanderlinde** [comment]
Very low priority:
Possible excerpt fade-in effect: http://demo.mekshq.com/?theme=herald (also see Ted.com)
Not quite accurate, since headline text should move up: http://codepen.io/anon/pen/YqPbja

**Comment by kjacks** [comment]
+ fix mouseover effect for text content
