### ISSUE TITLE
[𝛆] Stop using absolute url for timeline js

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1522]
Examples of instances where we're using absolute urls and shouldn't be:

- [x] https://github.com/newamericafoundation/newamerica-cms/blob/master/report/templates/report/pdf.html#L31
- [x] https://github.com/newamericafoundation/newamerica-cms/blob/master/report/templates/report/pdf.html#L44
- [ ] https://github.com/newamericafoundation/newamerica-cms/blob/master/newamericadotorg/templates/blocks/timeline.html#L67
- [x] We should do a project search to find any others, as well, and make them settings or similar.

**Comment by nmorduch** [comment]
check out EXTRA_STATIC_URL in settings, can pull that into the template

**Comment by nmorduch** [comment]
This has been causing problems while we're testing the Wagtail 10.2 update

**Comment by chigby** [comment]
Note: this was changed _to_ the absolute URL in #1518
