### ISSUE TITLE
New America Weekly

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#155]
Possible simple grid design approach http://themeforest.net/item/salient-responsive-multipurpose-theme/full_screen_preview/4363266

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-16 at 11 46 26 am](https://cloud.githubusercontent.com/assets/13524901/13818588/cfb6cd3a-eb6c-11e5-9d9e-cfb38d97bea1.png)

Using similar approach to blog posts, but with a different sidebar
@kjacks @sanajaved7 @FuzzHogan

**Comment by rossvanderlinde** [comment]
Some initial thoughts on how this could work (completely open to suggestions on this, but here's what I was thinking)

* Two templates: Weekly-Edition and Weekly-Post.
* When editing a new Weekly-Edition, you select from the posts you want to include, similar to how program staff choose which stories they want to promote on their homepages.
* The Weekly-Edition page includes all posts (in the above case, 5), listed one below the next. In other words, we have an 'infinite scroll' type of set up. When the user reaches the end of the first article, the second is directly beneath, and so on. Clicking on, say, the 3 Another Headline Goes Here button on the left sidebar scrolls the user to a bookmark/anchor on the page at the top of the third headline image.

**Comment by sanajaved7** [comment]
This looks great, @rossvanderlinde! In addition to the design, can I suggest that we (including @FuzzHogan and Emily) all meet at some point to discuss functionality (and vision) for the Weekly? 

Specifically, there are a few structural questions I'd like some clarity on since the Weekly will be operating pretty independently of the Program/Subprogram format everything else revolves around. It'd be great to nail that down so I can accurately estimate how long it will take to build this out.

**Comment by FuzzHogan** [comment]
Sure!
I'm in the office for one more week til Spring Break.
Shall we meet sometime Friday or Monday?

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-28 at 2 32 55 pm](https://cloud.githubusercontent.com/assets/13524901/14089429/e086b69e-f502-11e5-9b4e-c1b9a4598f4e.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-28 at 4 21 21 pm](https://cloud.githubusercontent.com/assets/13524901/14089436/e75b5c18-f502-11e5-94f5-b86fe44230a5.png)

**Comment by rossvanderlinde** [comment]
![newamericaweekly-designmar28](https://cloud.githubusercontent.com/assets/13524901/14089437/ecf0e8dc-f502-11e5-88e8-6475568e8f39.png)

**Comment by rossvanderlinde** [comment]
![weeklymag3-p3](https://cloud.githubusercontent.com/assets/13524901/14252865/2f8f8ab4-fa57-11e5-8353-49f2e87ad763.png)

**Comment by rossvanderlinde** [comment]
Similar, slightly simpler approach
![weeklymag4](https://cloud.githubusercontent.com/assets/13524901/14253796/f9dc8e86-fa5a-11e5-9f80-f67ba5c44d54.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-04-04 at 11 51 25 am](https://cloud.githubusercontent.com/assets/13524901/14253951/9bf532b8-fa5b-11e5-91e2-8e4c70098fd4.png)

**Comment by rossvanderlinde** [comment]
And this

![screen shot 2016-04-04 at 11 59 00 am](https://cloud.githubusercontent.com/assets/13524901/14254183/a6aad590-fa5c-11e5-9c0f-faef5387e012.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-04-04 at 12 27 42 pm](https://cloud.githubusercontent.com/assets/13524901/14255150/c2faedee-fa60-11e5-870c-fa63f722c03b.png)

**Comment by rossvanderlinde** [comment]
Getting closer...

![weeklymag5](https://cloud.githubusercontent.com/assets/13524901/14255430/eec6b984-fa61-11e5-8098-a69999368546.png)

**Comment by rossvanderlinde** [comment]
@kjacks the "getting closer" version is the final one

**Comment by rossvanderlinde** [comment]
Slightly more consistent fonts
![weeklymag5-cover](https://cloud.githubusercontent.com/assets/13524901/14263353/20a78548-fa88-11e5-8008-6a1aa082d3e6.png)

**Comment by kjacks** [comment]
@rossvanderlinde the editions on the home page will probably need to show their author too right?  In the design there is the bolded author name, but we have no way of somehow knowing to bold a name like that

**Comment by rossvanderlinde** [comment]
Is it plain text? @kjacks 
There are 1-2 people editing Weekly so they can be trained up on it if necessary. Unless it's a plain text field

**Comment by rossvanderlinde** [comment]
First attempt. I'm sure there'll be more tweaking
![weeklymag5-story](https://cloud.githubusercontent.com/assets/13524901/14264947/af84bbd6-fa8e-11e5-9575-2d23fc60a243.png)

**Comment by rossvanderlinde** [comment]
Bottom of weekly article @kjacks  ![screen shot 2016-04-06 at 9 25 27 am](https://cloud.githubusercontent.com/assets/13524901/14318160/982c4570-fbd9-11e5-87e3-bd1816fb5edb.png)

**Comment by rossvanderlinde** [comment]
i.e. taking you to the previous or next article in an addition
Just a suggestion

**Comment by kjacks** [comment]
@rossvanderlinde could definitely be a cool feature!  One thing is just consistency, because those blocks are bring used to represent editions, not articles, on the weekly homepage - and we are already dealing with some potential confusion between the two?

**Comment by sanajaved7** [comment]
@rossvanderlinde @kjacks - I think we need to discuss weekly functionality because it seems there's a disconnect between the structure we've built and desired functionality.
