### ISSUE TITLE
Our People Landing Page (Grid)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#156]
Currently the plan is to have three sections (tabs or separate pages):
- Board of Directors
- Staff
- Fellows

However, since Staff would include Program Fellows, which is potentially confusing, I think we need to have a further discussion with Fuzz, Maria, etc before proceeding with this.

**Comment by rossvanderlinde** [comment]
@sanajaved7 @kjacks after discussing further with comms team and comparing with other think tanks, we think tabs for each letter of the alphabet may be a good way to break up our 200+ bios in a relatively democratic way. A lot of other think tanks do the same thing (e.g. Carnegie) I'll work on a design update tomorrow. We'd still want dropdowns allowing results to be limited by Program name, and potentially whether they are Board of Directors / Experts / Support Staff

**Comment by rossvanderlinde** [comment]
Our people inside a program
![screen shot 2016-03-03 at 2 38 57 pm](https://cloud.githubusercontent.com/assets/13524901/13508333/85938b02-e154-11e5-9891-378e83fae1f0.png)

**Comment by rossvanderlinde** [comment]
Hopefully a simpler solution:

For programs:
![screen shot 2016-03-04 at 12 20 59 pm](https://cloud.githubusercontent.com/assets/13524901/13534802/f1c43c12-e204-11e5-8209-6105da6a4085.png)

Org-wide: (note that page numbers appear when the total number of items returned is greater than X)
![screen shot 2016-03-04 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/13524901/13534807/f4c69bbc-e204-11e5-97ad-c8a2f6affd43.png)

**Comment by rossvanderlinde** [comment]
The only difference between these models is 1) programs incorporates an "All Initiatives and Projects" dropdown instead of "All Programs" (and that dropdown is low priority, so if it needs to be added later that's okay) and 2) All Roles includes Board of Directors for org-wide

**Comment by rossvanderlinde** [comment]
Alternative approach for org-wide
![blogdesign-programlanding3](https://cloud.githubusercontent.com/assets/13524901/13725184/0eb1599a-e868-11e5-9e52-b755c31df52e.png)

**Comment by rossvanderlinde** [comment]
New Our People landing page per earlier discussion @kjacks @sanajaved7  @tylerrichardett @FuzzHogan

![ourpeople-p4](https://cloud.githubusercontent.com/assets/13524901/13861267/b29b58a0-ec62-11e5-94f5-6446fa10071e.png)

**Comment by rossvanderlinde** [comment]
Experts - is this what you had in mind @sanajaved7 ?

![ourpeople-p5](https://cloud.githubusercontent.com/assets/13524901/13861419/a5ba6e18-ec63-11e5-9d36-c311dba84e84.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-18 at 12 07 28 pm](https://cloud.githubusercontent.com/assets/13524901/13883930/11173940-ed02-11e5-9f67-b67651d1d857.png)

**Comment by kjacks** [comment]
@rossvanderlinde for the "find experts by program section" on the experts page - will these links take someone to the our people page for that program, but with the experts box checked?
