### ISSUE TITLE
Some reports not displaying until after an unreasonable wait

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1569]
Report with full bleed header image isn't working. See [in production](https://www.newamerica.org/education-policy/reports/transforming-financing/) vs [on na-develop](https://na-develop.herokuapp.com/education-policy/reports/transforming-financing/)

**Comment by nmorduch** [comment]
Possibly not actually a problem? We should try making another report have a full bleed image and see how it goes, just in case

**Comment by nmorduch** [comment]
Can't replicate. Will reopen if it comes up again

**Comment by nmorduch** [comment]
I think it might not actually be about the full bleed image. I was going to say this page was just displaying nothing but the header: https://na-develop.herokuapp.com/international-security/reports/world-drones/ but then I went back to check and it was fine. Also fine on the second load of the page, if you let it load a first time. Maybe something to do with images?

**Comment by chigby** [comment]
I'll report that all of the linked pages here loaded fine for me within < 5 seconds, both on production and the develop server.

**Comment by nmorduch** [comment]
Closed bc unable to reproduce, but I just experienced this again on staging (which would mean it was not related to the Wagtail update. I think that it happens the first time a report is ever viewed by anyone (so may be a caching thing). Might just be a dev/staging server slowness problem that we may not have in production.
