### ISSUE TITLE
Update Heroku apps to Cedar-14

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1577]
This isn't technically for the website but it's easier to put here

**Comment by nmorduch** [comment]
@jacobtoppm I made you a member on the Heroku org, which I think should be sufficient permissions

**Comment by jacobtoppm** [comment]
For data-projects, right now it isn't running. Is this intended, and if so, should it be upgraded? I can't find the repo for this either.

**Comment by nmorduch** [comment]
Fine to leave that one then!
