### ISSUE TITLE
[1hr📦] Investigate updating cairo

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1590]
> UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html

**Comment by chigby** [comment]
A couple of things I found:

1. The next major version of WeasyPrint (version 53, we are currently running 51) will drop cairo altogether: https://www.courtbouillon.org/blog/00004-weasyprint-without-cairo-what-s-different
2. It's possible we're only seeing this warning locally? The operating system on vagrant box we're using is Debian 9.4 (aka "stretch"), which seems to only support cairo version [1.14.8](https://packages.debian.org/stretch/libcairo2-dev). Whereas the `heroku-18` stack is running Ubuntu 18.04, which comes [preinstalled with cairo version 1.15.10](https://devcenter.heroku.com/articles/stack-packages). So this is looking to me like a situation where the dev/staging/production environment differs from the local development one.
