### ISSUE TITLE
Content Page - Updated Design

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#161]

**Comment by rossvanderlinde** [comment]
Image-less version:
![screen shot 2016-03-02 at 11 04 14 am](https://cloud.githubusercontent.com/assets/13524901/13466118/8adc2c3e-e066-11e5-927e-3b4cf175308c.png)

**Comment by rossvanderlinde** [comment]
Landing pages for Our Story, Our People, Issues, Funders, Advisory Councils, etc. take on the same two templates e.g.

![screen shot 2016-03-02 at 11 12 02 am](https://cloud.githubusercontent.com/assets/13524901/13466405/c99f3bcc-e067-11e5-9dac-e46f003a7317.png)
![screen shot 2016-03-02 at 11 14 34 am](https://cloud.githubusercontent.com/assets/13524901/13466449/f6938dc2-e067-11e5-9908-12d9abcebecb.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-02 at 12 08 32 pm](https://cloud.githubusercontent.com/assets/13524901/13468349/326dac12-e070-11e5-8ce3-ea8d27009c83.png)
![screen shot 2016-03-02 at 12 12 55 pm](https://cloud.githubusercontent.com/assets/13524901/13468353/35363270-e070-11e5-832b-16164972f2cb.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-02 at 12 07 50 pm](https://cloud.githubusercontent.com/assets/13524901/13468355/3a3b8540-e070-11e5-903c-942d450c0e9c.png)

**Comment by rossvanderlinde** [comment]
Consistent font styling and sizes:
![screen shot 2016-03-02 at 12 17 50 pm](https://cloud.githubusercontent.com/assets/13524901/13468494/ce92fb6a-e070-11e5-9e10-b04672ba27a5.png)

**Comment by rossvanderlinde** [comment]
Tagging @tylerrichardett for icons 

![screen shot 2016-03-02 at 12 26 32 pm](https://cloud.githubusercontent.com/assets/13524901/13468721/0edb2c0a-e072-11e5-9b19-cdda1034735d.png)
/

![screen shot 2016-03-02 at 9 27 22 am](https://cloud.githubusercontent.com/assets/13524901/13468778/5ec200f4-e072-11e5-8cfa-b72fc1312e47.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-02 at 1 33 32 pm](https://cloud.githubusercontent.com/assets/13524901/13470717/67484d92-e07b-11e5-9fa1-4111b3b4b70b.png)

**Comment by rossvanderlinde** [comment]
Author bio + subscribe box at the bottom:

![screen shot 2016-03-02 at 3 38 00 pm](https://cloud.githubusercontent.com/assets/13524901/13474612/d2c61d04-e08c-11e5-87a6-1bd71abc94db.png)

**Comment by rossvanderlinde** [comment]
@tylerrichardett do you think that subscribe icon is better?

**Comment by tylerrichardett** [comment]
@rossvanderlinde Better, though I'm personally a fan of envelope icons with the other two little lines:

![](http://cersys.ca/wp-content/uploads/2012/03/704px-aiga_mail-svg.png)

**Comment by rossvanderlinde** [comment]
@tylerrichardett can you please prepare that icon, or perhaps one with slightly more rounded edges, for kirk. Thanks!

**Comment by tylerrichardett** [comment]
@kjacks HTML/CSS for social icons: http://codepen.io/na-richardett/pen/bpVYKb

**Comment by tylerrichardett** [comment]
@kjacks SVG for subscribe icon attached

[envelope.svg.zip](https://github.com/newamericafoundation/newamerica-cms/files/159361/envelope.svg.zip)

**Comment by rossvanderlinde** [comment]
Great job @tylerrichardett !
