### ISSUE TITLE
Content Grid - Updated Design

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#163]
![screen shot 2016-03-02 at 3 47 41 pm](https://cloud.githubusercontent.com/assets/13524901/13474931/24c4fd40-e08e-11e5-8a9e-65b6396d5cc0.png)

**Comment by rossvanderlinde** [comment]
Note:
- In New America-level content grid, program logos should display. In program-level content grid, any initiative logos should display.

**Comment by kjacks** [comment]
I'm going to hold off on encoding that logic for when to display which until we can talk to Sana about how that will be handled from the backend side of things

**Comment by rossvanderlinde** [comment]
Sounds good. That logic seems a bit fuzzy to me anyway, so perhaps we can proceed with the design minus the program title blocks for the time being, and then potentially add those back in at a later point

**Comment by rossvanderlinde** [comment]
How's this for when there's no program selected?
![screen shot 2016-03-03 at 3 41 12 pm](https://cloud.githubusercontent.com/assets/13524901/13508775/6ba044c2-e156-11e5-90f3-7a8e425e5bc3.png)

**Comment by rossvanderlinde** [comment]
Alternative design when at New America level (not sure how complicated it is to do this)

![screen shot 2016-03-04 at 8 55 12 am](https://cloud.githubusercontent.com/assets/13524901/13528894/06d6e398-e1e7-11e5-800b-a56c0e1fc698.png)
