### ISSUE TITLE
New publication type: Brief

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1637]
Blocked by #1636

New publication type called Brief
- publication needs to be approved (#1636)
- [x] limit to 3k words ("brief" lol)
- [x] can have attached pdf
- [x] most similar to either a blog post or a policy paper
- [x] full-width DW charts need to work, etc (#1571)
- ~~pare down blocks available so there no legacy blocks (new page type doesn't need legacy things)~~

@chigby will do BE then @nmorduch will do FE

**Comment by chigby** [comment]
A couple questions:

1. When we limit it to 3,000 words, does that mean specifically the word count of the `body` field? As in, we want to count the words across all the blocks in the body and if the total is over 3k, the page is invalid and won't save? Or something else?
2. Do you have a list of which blocks are considered legacy blocks?
