### ISSUE TITLE
Search: subprogram pages that redirect should not show up in search

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1639]
see https://www.newamerica.org/search/?query=Cyber+Citizenship

There are two subprograms that show up. they both _look_ the same, but they link to different places. One is in ISP and isn't a real page, just redirects to the EPP one, and it should not show up in the list. (the "redirect" subprograms are imo a bad setup, but i don't think it's likely to be worth changing that setup to fix this)

**Comment by chigby** [comment]
I think this can actually be fixed in a way I haven't experimented with before but is straightforward to implement: excluding project pages with present `redirect_page` fields from being added to the search index in the first place.
