### ISSUE TITLE
OTI customization

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#167]
OTI needs a custom program block, because of their logo, and all instances of turquoise on their pages should instead be OTI blue.

Code to incorporate OTI logo in program title block (note that this is for a black logo -- @tylerrichardett can you please prepare a white version)

`h1.sidemenu__program-title__title:before {
    display: block;
    position: absolute;
    width: 37px;
    top: -6px;
    left: 0px;
    height: 60px;
    content: "";
    background: url('https://data.opentechinstitute.org/uploads/group/20141010-154738.919897opentechnologyiconblack.png') no-repeat 0 0;
    background-size: 100%;
}`

`h1.sidemenu__program-title__title { padding-left: 42px; font-size: .95rem; line-height: .9rem; }`

Preview of what that does (I had to use the dark version of the sidebar as the light version isn't yet up on elasticbeanstalk)

![screen shot 2016-03-03 at 12 23 26 pm](https://cloud.githubusercontent.com/assets/13524901/13502873/c9d51d7c-e13a-11e5-9308-fe3af3af723b.png)

**Comment by tylerrichardett** [comment]
@kjacks SVG of OTI logo attached

[oti.svg.zip](https://github.com/newamericafoundation/newamerica-cms/files/159379/oti.svg.zip)

**Comment by rossvanderlinde** [comment]
Still need to generate version of OTI logo in black box. https://app.asana.com/0/92711502709806/92711502709806 can you kindly assist.

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/58162393990584/58162393990584 I thought we decided against the black box for OTI?

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
I'll check in with Alison about whether OTI is okay with that. Alternative is adding a second image, one for mobile nav, one for desktop sidebar. We could then use a non-dark image for latter

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
I think that makes more sense. I'll generate a dark PNG tomorrow.

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
I'm going to check in with Alison about this, so hold off till I do. If it's a deal breaker I can ask Sana to add a separate image item to the program model now. I'm actually thinking that may be the best way to proceed because even if we address OTI, we still have the location based programs to figure out. It may be easier to add one variable than re-do OTI, DC, NYC, CA, and CHI

Ross van der Linde
Director of Communications
New America
740 15th Street NW, Suite 900, Washington DC, 20005
Office  (202) 596-3602 <tel:%28202%29%20596-3602>  |  Email vanderlinde@newamerica.org <mailto:vanderlinde@newamerica.org>  |  Twitter  @rossvanderlinde <http://www.twitter.com/rossvanderlinde>

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
