### ISSUE TITLE
Subscribe to Newsletter Page

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#168]
http://codepen.io/anon/pen/reVEXp

![screen shot 2016-03-03 at 4 12 31 pm](https://cloud.githubusercontent.com/assets/13524901/13510585/3dd020cc-e15f-11e5-87f1-907f52984434.png)

**Comment by rossvanderlinde** [comment]
Codepen backup

`
<div class="submission_form">
  <form action="http://newamerica.createsend.com/t/d/s/jdjrz/" method="post" id="subForm">
    
    <div class="row" style="padding-left:7px;">
      <b>Your Information</b>
    </div>
    <div class="row">
      <div class="medium-5 columns">
        <label for="fieldName">Full Name*
        <input id="fieldName" name="cm-name" type="text" required/>
      </label>
      </div>
      <div class="medium-5 columns">
        <label for="fieldEmail">Email*
        <input id="fieldEmail" name="cm-jdjrz-jdjrz" type="email" placeholder="Pre-populated" required />
      </label>
      </div>
      <div class="medium-2 columns">
        <label for="fieldtdkjdi">Zip Code*
        <input id="fieldtdkjdi" name="cm-f-tdkjdi" type="text" required/>
     </label>
      </div>
      <div class="medium-6 columns">
        <label for="fieldzuhg">Organization
        <input id="fieldzuhg" name="cm-f-zuhg" type="text" />
      </label>
      </div>
      <div class="medium-6 columns">
        <label for="fieldzuhw">Job Title
        <input id="fieldzuhw" name="cm-f-zuhw" type="text" />
      </label>
      </div>
    </div>
    
    <div class="row" style="padding-left:7px;">
      <b>Your Subscriptions</b>
    </div>
    <div class="row">
      <div class="large-2 medium-3 small-6 columns grayed"><label>
      
          <input id="listtkthyk" name="cm-ol-tkthyk" type="checkbox" /><br><span class="labelish">Asset Building Newsletters &amp; Events</span><span class="labelish2">Some more information goes here about Asset Building Newsletters</span>
   </label>
      </div>
      <div class="large-2 medium-3 small-6 columns grayed">Text
      </div>
      <div class="large-2 medium-3 small-6 columns grayed">Text
      </div>
      <div class="large-2 medium-3 small-6 columns grayed">Text
      </div>
      <div class="large-2 medium-3 small-6 columns grayed">Text
      </div>
      <div class="large-2 medium-3 small-6 columns grayed">Text
      </div>
    </div>


    </p>
    

    <p class="newsletter_divs">


      <label><input id="listtkthjr" name="cm-ol-tkthjr" type="checkbox" />Asset Building<span>Description Goes HereDescription Goes HereDescription Goes Here</span></label>


      <label><input id="listtkthtl" name="cm-ol-tkthtl" type="checkbox" />Breadwinning &amp; Caregiving Newsletters &amp; Events</label>
      <input id="listtkthtr" name="cm-ol-tkthtr" type="checkbox" /> <label for="listtkthtr">Breadwinning &amp; Caregiving Press Releases</label><br />
      <input id="listiudktd" name="cm-ol-iudktd" type="checkbox" /> <label for="listiudktd">Bretton Woods II</label><br />
      <input id="listikjhuh" name="cm-ol-ikjhuh" type="checkbox" /> <label for="listikjhuh">Cybersecurity Initiative - Global Cyber Quarterly Update</label><br />
      <input id="listikjyut" name="cm-ol-ikjyut" type="checkbox" /> <label for="listikjyut">Cybersecurity Initiative Newsletter &amp; Events</label><br />
      <input id="listikjhud" name="cm-ol-ikjhud" type="checkbox" /> <label for="listikjhud">Cybersecurity Initiative Press Releases</label><br />
      <input id="listirluv" name="cm-ol-irluv" type="checkbox" /> <label for="listirluv">Education Policy - DLL National Workgroup</label><br />
      <input id="listtkthtd" name="cm-ol-tkthtd" type="checkbox" /> <label for="listtkthtd">Education Policy - Early &amp; Elementary Ed</label><br />
      <input id="listtkthtt" name="cm-ol-tkthtt" type="checkbox" /> <label for="listtkthtt">Education Policy Newsletters &amp; Events</label><br />
      <input id="listtkthtu" name="cm-ol-tkthtu" type="checkbox" /> <label for="listtkthtu">Fellows - Newsletters &amp; Events</label><br />
      <input id="listtkthil" name="cm-ol-tkthil" type="checkbox" /> <label for="listtkthil">Fellows - Press Releases</label><br />
      <input id="listtkthiy" name="cm-ol-tkthiy" type="checkbox" /> <label for="listtkthiy">Future Tense - Newsletters &amp; Events</label><br />
      <input id="listtkthij" name="cm-ol-tkthij" type="checkbox" /> <label for="listtkthij">Future Tense - Press Releases</label><br />
      <input id="listtkthii" name="cm-ol-tkthii" type="checkbox" /> <label for="listtkthii">International Security - Newsletters &amp; Events</label><br />
      <input id="listtkthih" name="cm-ol-tkthih" type="checkbox" /> <label for="listtkthih">International Security - Press Releases</label><br />
      <input id="listtkthiu" name="cm-ol-tkthiu" type="checkbox" /> <label for="listtkthiu">New America NYC - Newsletters &amp; Events</label><br />
      <input id="listtkthdl" name="cm-ol-tkthdl" type="checkbox" /> <label for="listtkthdl">New America NYC - Press Releases</label><br />
      <input id="listdyjtn" name="cm-ol-dyjtn" type="checkbox" /> <label for="listdyjtn">Open Markets - Food and Farming</label><br />
      <input id="listtkthdr" name="cm-ol-tkthdr" type="checkbox" /> <label for="listtkthdr">Open Markets - Newsletters &amp; Events</label><br />
      <input id="listtkthdj" name="cm-ol-tkthdj" type="checkbox" /> <label for="listtkthdj">Open Markets - Press Releases</label><br />
      <input id="listtkthdt" name="cm-ol-tkthdt" type="checkbox" /> <label for="listtkthdt">Open Technology Institute - Newsletters &amp; Events</label><br />
      <input id="listtkthdd" name="cm-ol-tkthdd" type="checkbox" /> <label for="listtkthdd">Open Technology Institute - Press Releases</label><br />
      <input id="listtkthdh" name="cm-ol-tkthdh" type="checkbox" /> <label for="listtkthdh">Political Reform - Newsletters &amp; Events</label><br />
      <input id="listtkthhl" name="cm-ol-tkthhl" type="checkbox" /> <label for="listtkthhl">Political Reform - Press Releases</label><br />
      <input id="listijcm" name="cm-ol-ijcm" type="checkbox" /> <label for="listijcm">Profits &amp; Purpose Newsletters &amp; Events</label><br />
      <input id="listijcc" name="cm-ol-ijcc" type="checkbox" /> <label for="listijcc">Profits &amp; Purpose Press Releases</label><br />
      <input id="listdybti" name="cm-ol-dybti" type="checkbox" /> <label for="listdybti">Resilient Communities</label><br />
      <input id="listtkthhd" name="cm-ol-tkthhd" type="checkbox" /> <label for="listtkthhd">The Weekly Wonk</label>
    </p>
    <p>
      <button class="button" type="submit">Subscribe</button>
    </p>
  </form>
</div>`

`.newsletter_divs span {
  position: relative
}

html { padding-top:30px;}

.column:last-child:not(:first-child),
.columns:last-child:not(:first-child) {
  float: left;
}
.submission_form input[type="checkbox"] {
    line-height: 1em;
    margin-bottom: 0px;
    margin-right:0px;
  margin-left:0px;
  margin-top:0px;
}

.labelish { font-weight:800; font-size:1rem;  float:left; width:100%; }

html,
body,
label,
input {
  font-family: simplon bp !important;
}

input,
label { 
  padding:7px;
}

[type='email'],
[type='text'] {
  margin: 0px;
  padding: 0px;
  max-width: 100%;
}

.grayed {
  background-color: #eee;
  text-align:center;
  border: solid 7px #FFFFFF;
}

 p {
  line-height: 100%;
}

.submission_form .columns {
  padding: 0px;
}

.submission_form input {
  line-height: 1.5rem;
  padding-left: 8px;
}
`

**Comment by kjacks** [comment]
https://docs.google.com/spreadsheets/d/1Ek8shJNVPpyK1yv4xRQhzoD4gIldAjl4RggS564SmUo/edit?ts=57040bab#gid=0
