### ISSUE TITLE
AWS Cleanup -- audit keys & setup, tune instances, review costs

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/newamerica-cms#169]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113925245956637)

**Comment by rossvanderlinde** [comment]
Has this been completed? If so can we close

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by georgiamoon** [comment]
Updates from 6/8/16 call with Eddie (non-profit AWS accounts person):

- Learned about Trusted Advisor analysis that helps us by making recommendations of how to adjust our AWS tools and highlights security issues. Could help with cost optimization.
- Learned about tagging resources, Eddie following up with information
- Asked Eddie to send us information on training opportunities
- Non-profit team has Solutions Architects who can meet with us and help advise on deployment architectures that best meet our needs.

Next Steps:
- Review the Trusted Advisor Analysis
- Tag our resources and run some reports
- Schedule time with a Solutions Architect to discuss setup options and how to shift our setups now
