### ISSUE TITLE
[2h👀📦] Make subprograms work the same as programs

### ISSUE THREAD

**Issue by nmorduch** [newamericafoundation/newamerica-cms#1702]
If these used the same page model, then it wouldn't be such a pain when subprograms become full programs. We could have the extra fields for subprograms exists on in a dedicated tab in the page editor.

We also could then better represent the relationships between subprograms with multiple parent programs and their parents, but this would probably be a separate ticket since it would be more complicated.

**Comment by chigby** [comment]
My assessment of this project is that it would be doable but it would be a fair amount of work (particularly in copying all the data from subprograms to programs) for a questionable amount of gain. I think it might be better to prioritize smaller, less error-prone changes we can make more easily that will give us similar gains, such as: making Projects not a type of subprogram, or writing a script that automates the change of a _single_ subprogram into a program.

**Comment by nmorduch** [comment]
We decided that next time a subprogram turns into a program, we should probably write a generic script for doing it automatically.
