### ISSUE TITLE
Home Page - CSS Fixes

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#172]
* Left edge of Programs dropdown, lead story image, and first featured story image should line up `.picture-link { left:0px }  .small-12.large-4.columns { padding-left:0px; padding-right: 1rem !important; } `
* Buttons should be black with turquoise mouseover, not opposite. Only the support button is always turquoise.
* Dropdowns for our work and about can be thinner:` @media screen and (min-width: 40em) .header__simple-link-group { width: 225px; } `
* Text in top right corner can be made some gray color as footer text (presumably na-60%)
* In three story template, horizontal white margin between stories 2 and 3 shows up, but no vertical white margin between 1 and the others.
* Search bar still needs to be made into a border-box 1px solid.
* Our Story needs to be full width.
* Your e-mail Sign up —> Your Email Sign Up, and can remove exclamation after New America Weekly!
* Mouseover effect on top stories not consistent —> some are turquoise, others white, they need to have newamerica black. And` .hero-grid__element__overlay { background-color:rgba(44, 47, 53, 0.5) }`
* Border panels feedback TK

**Comment by rossvanderlinde** [comment]
`.hero-grid__element__text-bar { pointer-events:none }` At the moment if you mouseover the headline text in a top hero image, the background effect is lost; this css change allows the entire block to be responsive in the same way.

Lighter rather than darker mouseover effect on hero images seems to work better `.hero-grid__element__overlay:hover { background-color: rgba(44, 47, 53, 0.2);`

Subtle transition effects for hero images: `.hero-grid__element__overlay {  -webkit-transition: all ease-in 0.25s; -moz-transition: all ease-in .25s; -o-transition: all ease-in 0.25s; transition: all ease-in 0.25s; } .hero-grid__element__overlay:hover { background-color: rgba(44, 47, 53, 0.2); -webkit-transition: all ease-in 0.25s; -moz-transition: all ease-in .25s; -o-transition: all ease-in .25s; transition: all ease-in .25s; }`

**Comment by rossvanderlinde** [comment]
Tweaks to the events border panel
`.border-panel { border: 1px solid rgba(44, 47, 53, 0.2); height: 270px; } 
.border-panel__info { top:26px }
.border-panel__content h1 { margin-bottom:9px } .border-panel__circle-nav { bottom:19px } .border-panel__content h1 { line-height:100% }`

**Comment by rossvanderlinde** [comment]
Update: this works better. Sorry about the back and forth

`.hero-grid__element__background:before { background: -moz-linear-gradient(center top , rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0) 1%, rgba(0, 0, 0, 0.06) 16%, rgba(0, 0, 0, 0.4) 75%, rgba(0, 0, 0, 0.6) 100%) repeat scroll 0 0 rgba(0, 0, 0, 0); background: -webkit-linear-gradient(top , rgba(255, 255, 255, 0) 0%, rgba(0, 0, 0, 0) 1%, rgba(0, 0, 0, 0.06) 16%, rgba(0, 0, 0, 0.4) 75%, rgba(0, 0, 0, 0.6) 100%); bottom: 0; content: " "; display: block; height: 50%; left: 0; position: absolute; transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1) 0s; width: 100%; opacity: 1; z-index: 1; }

.hero-grid__element__overlay { background-color: rgba(44, 47, 53, 0.2); } 

.hero-grid__element__overlay:hover { background-color: rgba(44, 47, 53, 0); }`

It would still be good to incorporate the transition effects

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-08 at 10 20 40 am](https://cloud.githubusercontent.com/assets/13524901/13605834/71ce6288-e517-11e5-8d2a-d9b048e1efbf.png)

**Comment by rossvanderlinde** [comment]
Content in condensed top nav currently isn't vertically centered e.g. see how much closer logo is to baseline of navbar than top. This fixes it

`.header__logo svg { width: 45px; } .header__logo h1 { font-size: 1.2rem; padding-top:4px; width:100px } .header__content { padding: 3px 25px 14px 25px }`

**Comment by rossvanderlinde** [comment]
In mobile foldup, consistent font sizes: `.hero-grid__main .hero-grid__element__text-bar__heading { font-size:1.75rem } .hero-grid__element__text-bar__heading { font-size:1.75rem } `

**Comment by kjacks** [comment]
@rossvanderlinde should font sizes still remain different on wider screens between the main larger grid elements and the smaller secondary grid elements

**Comment by rossvanderlinde** [comment]
Yes I think so. Just looks strange on mobile when the boxes ar the same size
