### ISSUE TITLE
Integrating OAuth

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#18]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625164148)

**Comment by rossvanderlinde** [comment]
Added to June so we can at least discuss options, i.e. is it possible, can we contract out, how much work involved, security issues, what are the trade-offs etc

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
Ideally signing into wagtail wouldn't require a separate set of credentials, but could instead be administered through oauth integration.  Though there have been many requests for this form the Wagtail support groups, a seamless integration has yet to have been developed, so this is in many ways in a holding pattern until then
