### ISSUE TITLE
Sidemenu - CSS feedback (program title & heading spacing)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#182]
Program title box size and font, plus breadcrumb container and page title font
`.sidemenu__program-title__title { font-size:1.2rem } .sidemenu__program-title { width:163px } h1, h2, h3, h4, h5, h6 { line-height: 105% } @media screen and (min-width: 945px) .breadcrumb-container { padding-left: 0px; padding-top: 0px; padding-bottom: 20px; } `

**Comment by rossvanderlinde** [comment]
@kjacks what do you think about a bit of padding between headings like this?
![screen shot 2016-03-08 at 2 50 32 pm](https://cloud.githubusercontent.com/assets/13524901/13614182/3efcc0ae-e53d-11e5-86c1-3734506da0f1.png)


Here's the code
`.sidemenu__link-group { padding-top: 10px; }  li.menu-text.sidemenu__link-group__title { padding-top: 25px; }`

**Comment by rossvanderlinde** [comment]
Different browsers seem to handle vertical-alignment for display:table-cell differently. On my home computer (also using chrome) the default seems to be vertical-align:bottom, hence this page showed up as follows:

![screen shot 2016-03-08 at 8 51 46 pm](https://cloud.githubusercontent.com/assets/13524901/13622842/b7e71f00-e56f-11e5-9891-7b833bbc39ad.png)

Possible solution: make v-align explicit: `.sidemenu-container { vertical-align:top } ` Worked for me

**Comment by kjacks** [comment]
Hi Ross,

Cross-browser support is definitely something I need to delve into in the
next couple days - even things like table-cells, which are supported in all
the browsers still have strange little differences.  I opened up an issue
to address cross-browser for the header and home page and definitely want
to get to that soon.

Kirk

**Comment by kjacks** [comment]
Note: remove Subscribe from Sidemenu
