### ISSUE TITLE
Post - Podcast

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#199]
![screen shot 2016-03-10 at 8 56 02 am](https://cloud.githubusercontent.com/assets/13524901/13671441/f914426c-e69d-11e5-9ed7-e97d9fe14227.png)

**Comment by kjacks** [comment]
@rossvanderlinde this is another post type where inn our discussion we put it down as having the standard header image, where this design doesn't incorporate the image, should I go ahead and remove it?
