### ISSUE TITLE
In The News Post

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#211]
![screen shot 2016-03-14 at 11 44 37 am](https://cloud.githubusercontent.com/assets/13524901/13750048/3dced932-e9da-11e5-9a5b-501ff4a79f31.png)

**Comment by rossvanderlinde** [comment]
THis is what I was trying to find @georgiamoon @kjacks @sanajaved7

**Comment by kjacks** [comment]
@rossvanderlinde I know we had previously said that the Quoted design would have the standard header image at the top - does this mean we would be taking that out?

**Comment by rossvanderlinde** [comment]
It could have the standard header; in this particular case I was assuming that no header was added
