### ISSUE TITLE
Person Bio Page

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#225]
![screen shot 2016-03-18 at 11 35 52 am](https://cloud.githubusercontent.com/assets/13524901/13882915/b9e82354-ecfd-11e5-83a5-87c5babadfdf.png)

**Comment by kjacks** [comment]
@rossvanderlinde when you get the chance, we should figure out a couple things about the contact buttons:

- is the contact Kevin button bringing up a mailto dialog with his email as the recipient? or is it simply giving you his (or Maria's ?) email?
- if a person has twitter, facebook, linkedin, etc, are all of these appearing as separate buttons?
