### ISSUE TITLE
Content Grid - Date Picker

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#230]
Date picker. This is the design currently - let's talk further about it

![screen shot 2016-03-21 at 11 41 27 am](https://cloud.githubusercontent.com/assets/13524901/13924235/eb8898a4-ef59-11e5-8477-ef2760ed3cfa.png)

**Comment by kjacks** [comment]
http://tamble.github.io/jquery-ui-daterangepicker/
