### ISSUE TITLE
Post - Social share buttons

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#234]
Share buttons - how about these at the bottom of each article? http://js-socials.com/demos/ I can come up with a preview

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-28 at 4.36.04 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=118433992688143), [Screen Shot 2016-04-28 at 4.38.09 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=118433992688145)
#url https://app.asana.com/0/0/113929625099252/f
---[aa]

**Comment by kjacks** [comment]
use 'Icons with Count' with popup

**Comment by rossvanderlinde** [comment]
Need to add this js library to web pack build

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
+ can style with simplon

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
![screen shot 2016-05-31 at 1 43 51 pm](https://cloud.githubusercontent.com/assets/13524901/15684616/e70cd45c-2735-11e6-9f39-9d0ee78fe4c9.png)

Formatting the links so they are the same as other links:

`span.jssocials-share-label { font-size: 1.2rem; line-height: 1.65; font-family: Simplon; font-weight: 800; border-bottom: 2px solid #e0e0e1; padding-bottom: 2px; opacity: 1; color: #2c2f35; text-decoration: none; line-height: inherit; cursor: pointer; }`

Email on mouseover becomes #2ebcb3
Twitter becomes #5ba4ba
Facebook becomes #234a67

Left-align with paragraph text:
`.jssocials-share-label { padding-left: 0; }`

Create more padding between each:
`.jssocials-share { margin: .4em; }`

Add to some models that don't include it e.g. events

**Comment by kjacks** [comment]
+ add to events and weekly articles
