### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#243]

**Comment by rossvanderlinde** [comment]
Hope you don't mind me reopening this, @sanajaved7. I've changed it to low priority, so not necessarily for May. It's just the possible alternative approach to page numbers - interested to get feedback. Tagging @kjacks too

![screen shot 2016-03-23 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/13524901/13992570/fb36e3ec-f0f2-11e5-8f34-73e57a6f2675.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-23 at 12 33 49 pm](https://cloud.githubusercontent.com/assets/13524901/13992709/86b087b6-f0f3-11e5-984e-2c932b6e4cb2.png)
When there are other filters
