### ISSUE TITLE
Reading location

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#245]
![screen shot 2016-03-22 at 9 26 47 am](https://cloud.githubusercontent.com/assets/13524901/13953055/459ed84c-f010-11e5-914f-4baf3d5bf91c.png)
http://codepen.io/pankajparashar/pen/towxF
In this case, turquoise line would actually be thin and gray, and reading location turquoise bar would appear over it

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625167612)

**Comment by kjacks** [comment]
@rossvanderlinde just to be sure I follow the intended functionality
 - the color bar below the header should now be set to grey on pages where there is a progress bar
 - the progress bar should appear on all post pages I'm guessing - are there any additional pages it would need to appear on?

**Comment by rossvanderlinde** [comment]
To coincide with this change: `header { border-bottom: 2px solid rgba(44,47,53,0.1); }`

**Comment by rossvanderlinde** [comment]
I need to make a call on this after speaking to a few stakeholders and will then reassign back to you, Kirk

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
![screen shot 2016-06-15 at 12 03 04 pm](https://cloud.githubusercontent.com/assets/13524901/16087527/3cea6fc6-32f1-11e6-97f4-54af61af6bce.png)
@kjacks can we do this in the next week or two?

**Comment by rossvanderlinde** [comment]
Similar thing here http://www.bloomberg.com/politics/articles/2016-06-14/republican-senators-lose-hope-that-donald-trump-will-change

**Comment by LomaxRx** [comment]
currently mixed feelings about implementing this. tabled until more consensus if built.
