### ISSUE TITLE
Photo credit

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#248]
![screen shot 2016-03-22 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/13524901/13961965/3bd87528-f035-11e5-99f2-37b72c0f0cd3.png)

**Comment by rossvanderlinde** [comment]
Better/ easier approach, since captions can be long
![screen shot 2016-03-28 at 10 15 37 am](https://cloud.githubusercontent.com/assets/13524901/14079768/1c202fb2-f4ce-11e5-8c75-c9970893c66a.png)

**Comment by rossvanderlinde** [comment]
Ideally add a new field. If that's not possible, use the title field

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
Post Page header images should have source, but no caption
post body images should have source and caption
weekly images follow same logic as post images
images on home page, program landing page, and any content grids should have neither
