### ISSUE TITLE
Post - Related Content Block

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#251]
![screen shot 2016-03-22 at 2 19 16 pm](https://cloud.githubusercontent.com/assets/13524901/13962991/de71d758-f039-11e5-86f5-f76da1d25d2c.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113929625095924)

**Comment by rossvanderlinde** [comment]
Because of sidebar issue, let's slightly redesign
