### ISSUE TITLE
Book and Policy Paper Styling

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#270]
Very low priority, but the 3d book image isn't antialiased, something like this might help.

`.csstransforms3d .book { -webkit-transform-style: preserve-3d; }`

**Comment by rossvanderlinde** [comment]
http://stackoverflow.com/questions/6492027/css-transform-jagged-edges-in-chrome

**Comment by kjacks** [comment]
.csstransforms3d .book:before { width: 100%; left: 7.5%; background-color: #999; box-shadow: 5px 5px 20px #ddd; }
