### ISSUE TITLE
Topics Template (formerly Glossary and Issues Template)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#272]
Variation of content grid / issues pages, where we have a list of terms on the landing page, ordered alphabetically. Cybersecurity, Ed, Open Markets, and OTI all have possible uses for this. Not a May implementation, just adding as a future issue

**Comment by rossvanderlinde** [comment]
Box styling over two columns but can play with alternative designs. Looking forward to feedback.

Here are two possible versions...
![screen shot 2016-03-24 at 1 09 35 pm](https://cloud.githubusercontent.com/assets/13524901/14025097/aa211af6-f1c2-11e5-8d97-d42fef81e1f3.png)
![screen shot 2016-03-24 at 1 07 03 pm](https://cloud.githubusercontent.com/assets/13524901/14025096/aa1c6a06-f1c2-11e5-8924-8a48c29955a4.png)

**Comment by rossvanderlinde** [comment]
@kjacks @sanajaved7 @mariaelkin @tylerrichardett let me know what you think

**Comment by rossvanderlinde** [comment]
Also intro text is probably necessary

![screen shot 2016-03-24 at 1 35 07 pm](https://cloud.githubusercontent.com/assets/13524901/14025598/468efc62-f1c5-11e5-9856-5d39df34b2b7.png)

**Comment by rossvanderlinde** [comment]
Proposed structure:
- Edcyclopedia is the first tier of the hierarchy; the page is assigned the Topics Template
- Dual Language Learning, Federal Education Budget, Higher Education Programs, and Learning Technologies have been assigned as second tier pages. Their excerpt is used for the text under each heading, and their main paragraph content is used in the page that opens when you click on overview buttons.
- The light gray tabs are the third level pages underneath a given second level page.

**Comment by rossvanderlinde** [comment]
Without boxes

![screen shot 2016-03-24 at 1 53 33 pm](https://cloud.githubusercontent.com/assets/13524901/14026131/de0f1458-f1c7-11e5-92de-953c52bae4b7.png)

**Comment by georgiamoon** [comment]
@rossvanderlinde it might be nice to have horizontal lines between the blocks, but maybe not full boxes?

Questions: Are those tags or sections? I'm not sure that having them look like buttons/tags is right for what they are.

Also -- Will there be other topics/issue templates? Or would this be the main "issue area" landing view and then we'd have templates for one issue area that's more like what we looked at in WebStakeholders this AM?

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-28 at 11 46 10 am](https://cloud.githubusercontent.com/assets/13524901/14081862/cf214d6a-f4da-11e5-8f46-cf930c9da588.png)

**Comment by rossvanderlinde** [comment]
@georgiamoon @sanajaved7 @kjacks 

![screen shot 2016-03-28 at 11 47 37 am](https://cloud.githubusercontent.com/assets/13524901/14081882/ec2c87b2-f4da-11e5-9e5e-2532634cfbae.png)

**Comment by rossvanderlinde** [comment]
I'm not sure which I prefer

**Comment by sanajaved7** [comment]
@rossvanderlinde @georgiamoon @kjacks - for me personally the bullet points under FEB are easier to read

**Comment by rossvanderlinde** [comment]
Yeh I think I'm also leaning toward bullet points

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-28 at 12 28 01 pm](https://cloud.githubusercontent.com/assets/13524901/14082887/8bd4bca8-f4e0-11e5-9ed2-b247de8e6548.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-28 at 4 21 21 pm](https://cloud.githubusercontent.com/assets/13524901/14089156/69023ba8-f501-11e5-84e5-c3560cb1c9e2.png)
