### ISSUE TITLE
Home Page - When No Featured Stories

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#285]
- we need to at some point define behavior when new america home page or program/subprogram page has no featured stories, or less than 3 featured stories?

**Comment by rossvanderlinde** [comment]
Best solution for now is to probably just hide the feature blocks entirely in both cases

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde Yep, I added that logic in there - so I will go ahead and close this issue
