### ISSUE TITLE
Expert Search

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#321]
![screen shot 2016-03-30 at 10 29 58 am](https://cloud.githubusercontent.com/assets/13524901/14145592/6c86969a-f662-11e5-8b76-ad60f48d2974.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/113925245955926)

**Comment by rossvanderlinde** [comment]
-Search our Staff block can be removed temporarily from Our People page.
- Experts page temporarily just takes you to Our People
- Return to expert search issue in July/August

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by LomaxRx** [comment]
could the problem this is trying to solve be tackled by people's page redesign for issue #1043

**Comment by LomaxRx** [comment]
will be handled with #1043
