### ISSUE TITLE
Jobs Page Buildout

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#322]

**Comment by kjacks** [comment]
http://codepen.io/anon/pen/mPMxzz

**Comment by rossvanderlinde** [comment]
![screen shot 2016-03-30 at 12 10 04 pm](https://cloud.githubusercontent.com/assets/13524901/14149067/6956a6c8-f670-11e5-9636-62c332eaa3db.png)

**Comment by rossvanderlinde** [comment]
http://codepen.io/anon/pen/GZvdKe
