### ISSUE TITLE
Database transfer - In The News

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#350]

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/58162393990584/58162393990584 - Looks like there are 32 pages of In the News content for New America D.C. - does that seem high to you too? My suspicion is adding "New America" as a program for content to show up on the current site homepage has caused this. We could leave out all content tagged with that program id or add that to the clean-up that needs to get done.

Let me know how you want to proceed.

[--- Commented from Asana.com
#commenter Sana Javed
---[aa]

**Comment by rossvanderlinde** [comment]
Where is this pulling from? The general New America category? Are all items that were also tagged to a program removed already?

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
