### ISSUE TITLE
Subscribe - Confirmation Page

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#353]

**Comment by rossvanderlinde** [comment]
I think we just need to create a simple page with a confirmation message. Then set to Campaign Monitor.

https://app.asana.com/0/92711502709794/92711502709794 can you please create some text for this page and create a google doc for it. We were also thinking about offering people the opportunity to follow us on fb, tw etc after subscribing.

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
