### ISSUE TITLE
Hero Grid - Add Buttons for Events/Policy Papers

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#421]
- Past events: Watch the Webcast [takes you direct to Youtube/Ustream page] (But only if the webcast is given a separate field)
- Future events: RSVP [takes you direct to the RSVP page] (And similar functionality for actual event pages)
- Policy paper: View Paper [open the PDF]

**Comment by rossvanderlinde** [comment]
Currently just RSVP. Discuss other options with relevant stakeholders. Possible concern is driving traffic out of the site

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
