### ISSUE TITLE
Tidy up Printing

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#436]
Doesn't look terrible right now but could be better...

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-18 at 6.05.08 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=114025953385124)
#url https://app.asana.com/0/0/114025953385120/f
---[aa]

**Comment by kjacks** [comment]
Duplicate of #968
