### ISSUE TITLE
Editor Content Block: Gray Block

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#442]
For introductory text etc
https://cloud.githubusercontent.com/assets/13524901/13479023/2d83cbf0-e0a2-11e5-8e36-dd8a44899393.png

**Comment by rossvanderlinde** [comment]
Example of why we need it: http://www.newamerica.org/education-policy/edcentral/fix-free-college-1/

**Comment by rossvanderlinde** [comment]
Rich text field please

**Comment by LomaxRx** [comment]
- [ ] Add introduction block to [blocks.py](https://github.com/newamericafoundation/newamerica-cms/blob/786a0cf743d6955dc90bd8b89b4a7ff725f3ecf3/home/blocks.py#L11)
- [ ] Add introduction block to [Post model's streamfield](https://github.com/newamericafoundation/newamerica-cms/blob/786a0cf743d6955dc90bd8b89b4a7ff725f3ecf3/home/models.py#L398-L407)
- [ ] Add introduction block template to [`/home/templates/blocks/`](https://github.com/newamericafoundation/newamerica-cms/tree/786a0cf743d6955dc90bd8b89b4a7ff725f3ecf3/home/templates/blocks), (@kjacks are there other templates that need to be changed?)
- [ ] Add introduction block styling to [`/mysite/assets/scss/components/_post-body.scss`](https://github.com/newamericafoundation/newamerica-cms/blob/786a0cf743d6955dc90bd8b89b4a7ff725f3ecf3/mysite/assets/scss/components/_post-body.scss#L207)
- [ ] Data migration ...

**Comment by kjacks** [comment]
@LomaxRx this looks great!  The one thing that I would add would be that it probably should be added to simple pages as well - https://github.com/newamericafoundation/newamerica-cms/blob/786a0cf743d6955dc90bd8b89b4a7ff725f3ecf3/home/models.py#L221-L229

**Comment by LomaxRx** [comment]
staged
