### ISSUE TITLE
WYSIWYG Button: Citation

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#449]
Something like this perhaps http://www.bigfootjs.com/
Also nice approach http://harvardlawreview.org/2016/04/fresh-pursuit-from-indian-country-tribal-authority-to-pursue-suspects-onto-state-land/

Editing the WYSIWYG editor: https://jossingram.wordpress.com/2014/07/24/add-some-blockquote-buttons-to-wagtail-cms-wysiwyg-editor/

To achieve citation in sidebar see code snippet here https://github.com/newamericafoundation/newamerica-cms/issues/166

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/114062437577609)

**Comment by kjacks** [comment]
The idea here would be to add in text citations to the wysiwyg panel in richtext blocks on posts.  We have added custom blockquote and pullquote buttons to this editor panel in addition to the default set of options and the ability to have in text citations was flagged as another potentially useful feature
