### ISSUE TITLE
Editor Content Block: Content Promotion Card

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#451]
Display books, policy papers, events etc on a card.
Including people (our people and external authors)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/114062437577684)

**Comment by rossvanderlinde** [comment]
http://www.newamerica.org/oti/ranking-digital-rights/rdrs-people/

**Comment by kjacks** [comment]
This is a fairly complicated proposal, but essentially would entail creating content promotion cards that could be added to posts or other pages on the site which would allow the user to highlight similar pieces or other work that new america has done on a given topic.  It is awaiting design and a full discussion of what the ideal functionality would be.
