### ISSUE TITLE
Sort Page Explorer Alphabetically

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#454]
Is it possible to sort by alpha in the "Choose a page" explorer?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/114006120336693)
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;114006120336699">possible to alphabetize.PNG</a>

**Comment by sanajaved7** [comment]
@rossvanderlinde - will check on this and report back.

**Comment by LomaxRx** [comment]
active discussion on solution to this [here](https://github.com/torchbox/wagtail/issues/882). will check back in a few months for progress.
