### ISSUE TITLE
Add Links to Remaining Org-wide Static Pages

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#459]
Top Menu Mobile - Context, Our Story
Top Menu Desktop - Context, Our Story
Home Page - Our Story
Footer - Policies & Procedures, Creative Commons

**Comment by rossvanderlinde** [comment]
I need to finish doc

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
Still need to add Policies & Procedures, Creative Commons to footer. Tagging @mariaelkin -- if necessary ask Jeff to assist

**Comment by mariaelkin** [comment]
I created the pages and sent Kirk the links yesterday.

On Wed, May 18, 2016 at 12:27 PM, rossvanderlinde <notifications@github.com>
wrote:

> Still need to add Policies & Procedures, Creative Commons to footer.
> Tagging @mariaelkin <https://github.com/mariaelkin> -- if necessary ask
> Jeff to assist
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newamericafoundation/newamerica-cms/issues/459#issuecomment-220082138>
>



-- 

Maria Elkin

Communications Associate

New America

740 15th Street NW, Suite 900, Washington DC, 20005
Office  *(202) 986-2700 <%28202%29%20986-2700>*  |  *Direct **(202)
847-4769 <%28202%29%20847-4769>*  |  Email elkin@newamerica.org  |  Twitter
 @mvelkin <http://www.twitter.com/mvelkin>

**Comment by rossvanderlinde** [comment]
@kjacks
