### ISSUE TITLE
Database Transfer - Update Article Script

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#471]
- Generate CSV and update script to account for which former articles actually need to be created as blogposts

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/93344036160798/93344036160798 let's have a conversation tomorrow (Friday) to figure out how to handle articles/blogposts in the db transfer based on that csv.

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/58162393990584/58162393990584 happy to chat about that when you are available. Saw your email about the remaining 1680 uncategorized articles. If you could describe the process you used to determine the categories of the ones you already did, that would be very helpful.

[--- Commented from Asana.com
#commenter Jeff Back
---[aa]
