### ISSUE TITLE
Images in posts should have min-height

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#475]
Height of story images in posts is currently set based on amount of padding in .with-image .post-header__text. Would be ideal to set images to be 300px high, with text in box vertically centered underneath.

**Comment by rossvanderlinde** [comment]
Ideally now, can be later in May/June if necessary

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
Actually this logic already exists for blog posts, which have images set to a specific height. So hopefully that can just be applied to other post types too (although height 300px rather than 450px)

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
@ross this change is in master already - should be visible for the next deployment!

**Comment by ross** [comment]
> @ross this change is in master already - should be visible for the next deployment!

Wrong @ross, looks like you want @rossvanderlinde

**Comment by kjacks** [comment]
woops, sorry about that @ross
