### ISSUE TITLE
Cover attribute for Our People circle images

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#482]
Currently the .person__icon__photo class has the property background-size:cover but that's being overridden by the background property. That results in images that aren't squares not extending to the full dimensions of the circle. 

See image for evidence that background is suppressing the background-size attribute. There may be other solutions but a hacky !important works:
`.person__icon__photo { background-size:cover !important } `

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 12.59.39 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115022588594921)
#url https://app.asana.com/0/0/115022588594918/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde yep this issue is solved in the next deployment of elastic beanstock
