### ISSUE TITLE
Event content grid CSS

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#487]
Slide up panel should take up full box.

I added a new 0.3 gray. We need it. 0.15 is too light for text, 0.7 too dark for these purposes (but necessary elsewhere)

`.picture-grid__entry__text-container { padding:25px } 
.picture-grid__entry__title a { color: #2c2f35; font-weight: bold; font-size: 26px; font-family: simplon; line-height: 105%; }
h5.picture-grid__entry__title { padding: 8px 0px; }
.picture-grid__entry__date-time { color: #2c2f35; font-weight: bold; font-size: 15px; margin-bottom: 0px; }
.picture-grid__entry__location { color: rgba(44, 47, 53, 0.3); font-weight: bold; font-size: 15px; }
`

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 2.24.25 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115022588594937)
#url https://app.asana.com/0/0/115022588594932/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde do you have a new america black .3 equivalent that you like?
