### ISSUE TITLE
Bullet Points and Numbers Not Displaying

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#500]
Both the numbered and bulleted lists did not display properly

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 4.29.47 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583075)
#url https://app.asana.com/0/0/115014319583072/f
---[aa]

**Comment by rossvanderlinde** [comment]
Add lists to paragraph formatting style
`.post-body p, .post-body blockquote, .post-body li { etc etc `

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
To style numerical lists
`.post-body ol li { display: list-item; list-style-type: decimal; margin-left: 25px; }`
To style bullet point lists
`.post-body ul li { display: list-item; list-style-type: disc; margin-left: 45px; }`

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
Small fix on the css on this:

`ul, ol, dl { margin-bottom:1rem } ` is unfortunately being overridden by the ul element which has margin:0. That means the unordered list has no bottom padding. See:

http://newamerica-cms-dev.elasticbeanstalk.com/political-reform/press-releases/next-social-contract/

**Comment by kjacks** [comment]
@rossvanderlinde I'm not seeing the missing margin - maybe this was from a previous deployment?

![screen shot 2016-04-27 at 9 34 26 am](https://cloud.githubusercontent.com/assets/6720200/14853876/5442a1b4-0c5b-11e6-9e48-c103e9d9ceb4.png)
