### ISSUE TITLE
Photo Alignment Settings Not Working

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#501]
I set a photo to right align, and the published version is left aligned

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 4.29.41 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583071)
#url https://app.asana.com/0/0/115014319583068/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde - was this before the new deployment or after? It was working for me now
