### ISSUE TITLE
If author has no short bio or photo, word "Host" appears with nothing after it.

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#508]
Under the word "Host:" or "Author:" at the bottom of the page if the author has no bio then nothing shows up.

Best solution is probably to make sure everyone has a bio.

Creating a new 'May Cleanup' tag for things for temp and comms team to work on prior to launch.

**Comment by kjacks** [comment]
@rossvanderlinde I'll set a fallback to at least show the author's name, if they have neither of the other fields

**Comment by rossvanderlinde** [comment]
Sounds good. I think we'll make sure all NA authors have a short bio at least.
