### ISSUE TITLE
Line of text beneath embedded videos

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#511]
Issue flagged by Amanda: Ustream currently returns an unnecessary div below the iframe video embed of ustream content, reading: "Live Video app for Facebook by Ustream."

Since it's not within the iframe, but in a div beneath, it can be removed with the following hacky solution:

`.responsive-object a { display: none !important; }`

Unfortunately the a tag doesn't have a class so being more precise about the class we're selecting is difficult. I don't think ".responsive-object a" would select anything other than this piece of text so I think that's a relatively safe solution, at least for the time being

**Comment by kjacks** [comment]
@rossvanderlinde I'm not sure what to do on this one, because if we take out all a tags from any embedded iframes, I think we're going to run into problems with other embeddable content - in which there is a high likelihood that there will be links

**Comment by rossvanderlinde** [comment]
`.responsive-object a[href^="http://www.ustream.tv/"][target=_blank] { display: none !important; }`
