### ISSUE TITLE
Lost the Sidebar on Bio Pages

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#514]
We should still have the 'About' sidebar on the individual bio pages--maybe with the highlighted word as whichever section the person is in. But we'll have to figure out how that would work for the few cross-listed people, like Anne Marie.

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 1.48.53 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583056), [Screen Shot 2016-04-20 at 1.49.37 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583058)
#url https://app.asana.com/0/0/115014319583053/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde we can definitely add the about sidebar to bio pages if that's a desired addition, but the active link will only be able to highlight our-people, because it is based on the url

**Comment by rossvanderlinde** [comment]
Could potentially come back to this after launch

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
Cool, let's do that

**Comment by kjacks** [comment]
Leaving Bio Page without sidemenu, as per conversation 4/22
