### ISSUE TITLE
Font in 'About X' at the bottom of homepage and program pages too big

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#516]

**Comment by rossvanderlinde** [comment]
Agreed.
Some other css tweaks to about boxes:

`.border-panel { margin-bottom:0px } 
.panel h1 { font-sizes:2rem; line-height: 100%; }
.panel p { opacity: 0.7; margin: 20px auto 0px; font-size: 1.25rem; }`
Plus need to add Read More button if it hasn't already been added

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde the read our story button only appears if the program has added an about us page in the editor - I figured this would help us avoid dead links
