### ISSUE TITLE
Uploading a Photo - "Tags" Field?

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#519]
What is this field?

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 1.33.05 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583037)
#url https://app.asana.com/0/0/115014319583034/f
---[aa]

**Comment by rossvanderlinde** [comment]
Some help text may be in order. Or we can just return to this in the summer

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
Field used to categorize images in the editor, not currently being used
