### ISSUE TITLE
Personal Social Media Info

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#520]
Doesn't seem to appear anywhere

**Comment by kjacks** [comment]
@rossvanderlinde right, we still haven't decided what the contact buttons on a person's bio do - Outstanding Issue #300

**Comment by rossvanderlinde** [comment]
Reverting back to #300 and closing

**Comment by rossvanderlinde** [comment]
Not essential they're there by launch, so could shift to June

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
Should appear below bio next to contact button

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
