### ISSUE TITLE
CSS: Homepage Footer Padding

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#521]
Remove gap between footer and page content, but only on website homepage.

This seems to achieve that neatly:
`.header--expanded .footer { margin-top: 0px; }`

**Comment by kjacks** [comment]
@rossvanderlinde that line will remove it on all pages. 
- will the margin also disappear on program landing pages?

**Comment by rossvanderlinde** [comment]
Homepage and profile pages only

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]
