### ISSUE TITLE
Remove Search Box from Content Grids, Picture Grids, Our People Page, and Experts Page

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#525]

**Comment by kjacks** [comment]
@rossvanderlinde I just wanted to flag that we now have kind of a floating pagination 
![screen shot 2016-04-22 at 12 25 53 pm](https://cloud.githubusercontent.com/assets/6720200/14748071/b0f309c8-0885-11e6-8e90-f052281a55c7.png)

**Comment by rossvanderlinde** [comment]
I think so long as it's right aligned that's okay!

Ross van der Linde

Director of Communications

New America

740 15th Street NW, Suite 900, Washington DC, 20005
Office  (202) 596-3602  |  Email vanderlinde@newamerica.org  |  Twitter
@rossvanderlinde <http://www.twitter.com/rossvanderlinde>
