### ISSUE TITLE
Simple Page Model Template Selector

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#540]
To provide greater flexibility for the simple page model, and in particular allow it to cater for new content types (speeches, testimony, legislative filings, etc) we discussed the possible addition of a field to simple pages, allowing the following to be selected for landing page templates:

- Text Only Template (Simple page with text)
- Two-Column Content Grid (Per the current issues model)
- Single-Column Content Grid (Per the current content grid model)
- Card Content Grid (Per the event and weekly model)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/116085151172836)

**Comment by sanajaved7** [comment]
http://docs.wagtail.io/en/v1.5.2/topics/pages.html#changing-the-template

**Comment by rossvanderlinde** [comment]
With priority focus on choice between text-only and single-column standard content grid.

Note: would require adding date & author fields, but wouldn't be mandatory. And would therefore need ordering fall back (date modified/ alphabetical title/whatever)

**Comment by rossvanderlinde** [comment]
Note: primarily for programs with newsletters like assets and OTI's various content types, so liaise with Justin and Alison

**Comment by kjacks** [comment]
There have been requests from the site's launch for content types in addition to the standard set (policy paper, blog post, event, etc.).  These requests have included support for speeches, legislative filings, and a few others.  Essentially there would be no difference in the actual templates or models for these content types but programs would like to be able to categorize post content in additional ways.

One possible solution for this request would be to allow users to select the template they wish to use when creating a simple page, allowing them to select from the traditional simple page, a content grid to house subcontent, and a few others listed above.

There are other solutions, including developing an unnamed post type where the name could be set in the editor, and behavior would follow other post type setups.  This one definitely merits further discussion when we come to it
