### ISSUE TITLE
Bio needs related content beneath promoted content

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#550]

**Comment by sanajaved7** [comment]
![biopagedesign](https://cloud.githubusercontent.com/assets/7397798/16271413/e9265bee-3867-11e6-980c-774a0b2837e5.png)

**Comment by rossvanderlinde** [comment]
On page 2 and onwards the bio text and any featured content is hidden, leaving only the icon, name, job title, and second page of results
