### ISSUE TITLE
Mobile Post CSS: Padding on body text and images

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#564]
Currently:
- Text is tight up against edge of window. I know it's aligned with the left of the NA logo, but I think in this case it just makes reading difficult. Typically mobile and tablet body text has  padding.
- When content like images and video are wider than the rest of the mobile screen, it takes the text with them off the right edge of the screen.
- Images ought to lose right alignment on mobile, and just display normally.
- I added some top and bottom padding to images in mobile, which I think will be especially necessary when we have captions in there.

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-26 at 9.59.19 AM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=116877442514674), [Screen Shot 2016-04-26 at 9.58.17 AM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=116877442514676)
#url https://app.asana.com/0/0/116877442514667/f
---[aa]

**Comment by kjacks** [comment]
1. Resolved in #576
2,3,4. Covered in Issue #573
