### ISSUE TITLE
Lead Stories on Homepage CSS

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#566]
`.hero-grid__element__text-bar__subheading { display: inline-block; margin-bottom: 7px; font-size: 14px; font-weight: bold; color: #fff; line-height: 100%; text-transform: uppercase; letter-spacing: 0.5px; }`
Changes:
- Content type to 14px with 0.5px letter spacing (will be reflected on other pages too)
- Slight bottom margin
- White text

Also, can content type = articles and op-eds just say 'Article' rather than 'Articles and Op-Ed' on the homepage top stories and when categories are displayed in search results and content grids?

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-26 at 10.09.37 AM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=116877442514687)
#url https://app.asana.com/0/0/116877442514681/f
---[aa]

**Comment by kjacks** [comment]
@sanajaved7 thoughts on changing the verbose name of articles & op-eds to just Articles.  
It is hard-coded as Articles & Op-eds everywhere on the site except where the content type is listed in the hero-grid/content-grid.

**Comment by sanajaved7** [comment]
@rossvanderlinde @kjacks Definitely open to that but changing the verbose name will change it across the site, including inside the editor. If I remember correctly, we gave it a more elaborate name to distinguish it from the "In the News" type and to clarify for users that this content type includes op-eds. I'll defer to @rossvanderlinde if we still want to make that clear via this name or if it's something the handbook/training can cover.

**Comment by kjacks** [comment]
@sanajaved7 absolutely, I agree that it's useful within the editor to make that distinction.  If necessary, could also add a conditional in the template to display article instead of article and op-ed

**Comment by rossvanderlinde** [comment]
@kjacks @sanajaved7 just to clarify I was only referring to where it says 'article and oped' in the homepage lead stories. It makes sense to have "Articles and Opeds" on the dropdown, as the content grid features both. But where we're referring to a single item, it doesn't make sense to say both articles and opeds because it is only one of the two. Let's talk later about how best to make that work (and whether it requires changing the name universally or just in some places)

**Comment by rossvanderlinde** [comment]
Related issue: for simple pages, I think the text saying 'Program Simple Page' could say something generic like 'Featured Work' or just be blank. Will get feedback
![screen shot 2016-04-28 at 12 44 39 pm](https://cloud.githubusercontent.com/assets/13524901/14893880/12cfe810-0d3f-11e6-994f-90193eedd1d4.png)
