### ISSUE TITLE
Date numbers - can we get rid of 0?

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#603]
Can we get rid of the '0' that displays before numbers below 10?

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 5.00.07 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583109)
#url https://app.asana.com/0/0/115014319583106/f
---[aa]

**Comment by kjacks** [comment]
Duplicate
