### ISSUE TITLE
Desktop: [IE] Home page: Several elements of page are shown wrong (Incorrect position, broken layout)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#610]
Browser: IE11 
Pages: http://newamerica-cms-dev.us-west-2.elasticbeanstalk.com
http://newamerica-cms-dev.us-west-2.elasticbeanstalk.com/better-life-lab/books/article-1/

1. Buttons' position is incorrect (It's lower than it should be)
2. Magnifying glass white area leak at search box
3. Social network icons shown as column

[--- This issue is linked with an Asana task
#attachments [IE_2016-04-28_5-11-24.png](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793562), [IE_2016-04-28_5-11-24_2.png](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793564), [IE_2016-04-28_5-14-12.png](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793566)
#url https://app.asana.com/0/0/118079082793557/f
---[aa]

**Comment by kjacks** [comment]
First two fixed
