### ISSUE TITLE
iOS: [Any] Context menu issue when collapsing sub menu after going back to page

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#612]
iOS (iPhone+iPad)
Browser: Chrome+Firefox
1. Open http://newamerica-cms-dev.us-west-2.elasticbeanstalk.com 
2. Open context menu
3. Enter something to search box and proceed with search, or just tap any of links of that menu
4. Go back to that page by "Back" button
(You are at home page with context menu already open)
5. Collapse submenu

Result: SubMenu starts to collapse/expand in loop (see video attachment)

[--- This issue is linked with an Asana task
#attachments [20160428_052838_1.mp4](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793570)
#url https://app.asana.com/0/0/118079082793567/f
---[aa]

**Comment by kjacks** [comment]
- 5/3 - unable to replicate error
