### ISSUE TITLE
iOS: [Chrome] iPhone: Tiny transparent line between UI of browser and top menu bar

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#614]
iOS: iPhone 5s
Browser: Chrome / Portrait
Page: https://newamerica-cms-dev.us-west-2.elasticbeanstalk.com

There is tiny transparent line between UI of browser and top menu bar (You can see page content there when perform scrolling)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/118079082793589)
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;118079082793592">IMG_0142.PNG</a>

**Comment by kjacks** [comment]
5/3 - error replicated on iphone 5s + Chrome, need debugging platform for iOs + Chrome/Firefox
