### ISSUE TITLE
Build out content homepage filter functions

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#620]
- Filter by program
- Filter by date
- Filter by initiative when inside program

**Comment by sanajaved7** [comment]
@rossvanderlinde - Filter by initiatives is only going to be at the program level since subprograms can't have subprograms/initiatives. Do you still want the date filter at the subprogram level?

**Comment by rossvanderlinde** [comment]
Hey @sanajaved7, yes I think the options would be as follows (but let me know if this is all feasible):

**Global content grid**
Filter by program and date

**Program content grid**
Filter by initiative and date

**Initiative content grid**
Filter by date

**Search results**
Filter by program, date, and content type

**Comment by rossvanderlinde** [comment]
Wait, is there even going to be an initiative content grid? How would anyone access that?
