### ISSUE TITLE
'In The News' still says 'Quoted' and program dropdown should say 'All Programs' not 'All Initiatives'

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#621]
[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-04-20 at 4.58.02 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=115014319583105)
#url https://app.asana.com/0/0/115014319583102/f
---[aa]

**Comment by rossvanderlinde** [comment]
Assigning to https://app.asana.com/0/113884670727555/113884670727555 although I think this may have already been resolved

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde  these are just dummy placeholders, that will change when we implement the filters
