### ISSUE TITLE
Images not showing for simple pages

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#625]
Not displaying either when used as feature stories or in the actual simple page.
![screen shot 2016-04-28 at 12 41 10 pm](https://cloud.githubusercontent.com/assets/13524901/14893733/8bef5d62-0d3e-11e6-8b46-7629d333a26c.png)

Also noticed the simple pages need regular post formatting applied to them.

**Comment by kjacks** [comment]
@rossvanderlinde - I got simple pages into the features and lead stories, the one thing is just that the label will say program simple page
![screen shot 2016-04-28 at 3 08 32 pm](https://cloud.githubusercontent.com/assets/6720200/14898112/34c305a6-0d53-11e6-9c04-46b137079714.png)
