### ISSUE TITLE
Bug: Can't add book cover

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#626]
in here http://newamerica-cms-dev.us-west-2.elasticbeanstalk.com/admin/pages/150/edit/

![screen shot 2016-04-28 at 12 56 19 pm](https://cloud.githubusercontent.com/assets/13524901/14894250/b2e35d18-0d40-11e6-97ea-f77722a6234f.png)

**Comment by sanajaved7** [comment]
Hey @kjacks do you know why it would be still looking for the images in the wagtailimages model?
