### ISSUE TITLE
Mobile: Slider controls have different color of elements upon tapping one of them

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#644]
Device: LG G3
Problem: Once I've tapped < or > element of slider it becomes black and other one remains gray, so it's seems like it's unavailable to move to previous slide
Solution: Fix color of elements (Let it be gray or black statically)

[--- This issue is linked with an Asana task
#attachments [QuickMemo+_2016-04-25-23-13-34.png](https://app.asana.com/app/asana/-/download_asset?asset_id=116640465869539)
#url https://app.asana.com/0/0/116640465869535/f
---[aa]

**Comment by kjacks** [comment]
Investigated 5/2 - Due to android maintaining focus on element until next element is focused
