### ISSUE TITLE
Android: [Internal] Home page: Page is rendered incorrectly (Completely broken layout)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#655]
Android: Ainol Hero 10 Tablet
Browser: Internal browser
Page: http://newamerica-cms-dev.us-west-2.elasticbeanstalk.com

Just open page

[--- This issue is linked with an Asana task
#attachments [20160428_063319.jpg](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793606), [20160428_063333.jpg](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793608), [20160428_063352.jpg](https://app.asana.com/app/asana/-/download_asset?asset_id=118079082793610)
#url https://app.asana.com/0/0/118079082793603/f
---[aa]

**Comment by rossvanderlinde** [comment]
Happens for all of pages, guess because of top menu
https://docs.google.com/spreadsheets/d/10ZEoXqfXmgjClVAg-Qy8WXODj70hGcClecgp9-YbgaY/edit#gid=0

[--- Commented from Asana.com
#commenter Sergey Flakon
---[aa]

**Comment by kjacks** [comment]
Not sure which browser is built in with this device, but any issues have been resolved on other android tablets
