### ISSUE TITLE
Bold text formatting in post

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#689]
Bold/strong text in post needs to be dark black. See how Ross Schulman's name is too light in the version below (because the .7 opacity black is being applied)

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-05-05 at 2.32.52 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=124595753027858)
#url https://app.asana.com/0/0/124595753027853/f
---[aa]

**Comment by kjacks** [comment]
This is due to the b and strong tags - will add styling for both

**Comment by kjacks** [comment]
Related Bolding Issue: transferred content has strange nested divs within body that mess up the dropcap/first paragraph bolding logic 
![screen shot 2016-05-05 at 2 52 33 pm](https://cloud.githubusercontent.com/assets/6720200/15053607/60208e34-12d1-11e6-89ce-fed837df33b6.png)

![screen shot 2016-05-05 at 2 52 40 pm](https://cloud.githubusercontent.com/assets/6720200/15053609/642e6a6e-12d1-11e6-93cf-305fd4102352.png)
