### ISSUE TITLE
Bug - Events grid scroll up spilling into other events

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#698]
<img width="920" alt="screen shot 2016-05-05 at 4 10 30 pm" src="https://cloud.githubusercontent.com/assets/7397798/15055688/edd46bba-12db-11e6-9d77-3917ef8dc91a.png">

**Comment by sanajaved7** [comment]
@kjacks feel free to close if this is a duplicate of #690

**Comment by kjacks** [comment]
yep!
