### ISSUE TITLE
Weekly Issues in Wrong Order

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#713]

**Comment by kjacks** [comment]
@sanajaved7 we can actually just drag them in the editor to change the order

**Comment by sanajaved7** [comment]
@kjacks good point. I realized it's because the edition number are strings and not integers so that's why the sorting is all wonky. There's a method we can pass to the queryset to cast the string to int but it's being deprecated and this is a better solution so I'll delete this issue and that branch.
