### ISSUE TITLE
Add em dash to WYSIWYG editor

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#724]
Please add an em dash button to the editor!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/129896922566962)

**Comment by LomaxRx** [comment]
pretty sure this is not possible and probably unnecessary. em dashes can be added with keyboard shortcuts shift+option+minus on mac or alt+ctrl+minus on windows or copy and pasted.
