### ISSUE TITLE
Ustream embeds not working because of http/https mismatch

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#725]

**Comment by sanajaved7** [comment]
http://docs.wagtail.io/en/v1.0b1/howto/settings.html?highlight=embedly

**Comment by georgiamoon** [comment]
Left you a note on slack, but I'll also update here.

On the old website, the ustream embed does seem to have an https link. I tried in the dev tools, just adding an 's' to the ustream url for the record, and that seemed to fix it. 

Is the issue of not having the 's' as part of the URL coming from the URL that's stored in the old CMS? or where/how did you port that content?

**Comment by sanajaved7** [comment]
Reassigning to @kjacks

**Comment by sanajaved7** [comment]
Hey @kjacks this snippet should help if you're interested in trying the approach to override the save method:
```
from wagtail.wagtailembeds.models import Embed

embeds = Embed.objects.all()

embeds[4].html = embeds[4].html.replace('http:', 'https:')

embeds[4].save()

```
