### ISSUE TITLE
Allow Initiatives to Be Removed from Programs Dropdown

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#726]
June project: can we limit subprograms that appear in the programs dropdown to only those that have "Show in Menus" selected?

This will allow us to not show retired/archived initiatives while still categorizing content in that initiative.

**Comment by rossvanderlinde** [comment]
@kjacks I tried setting global assets to not show in menus and it still appears in the programs dropdown

**Comment by kjacks** [comment]
@sanajaved7 Let me know what you're thinking as to alternate solutions to this.  The pr is there and ready to go if need be, but if there is a better way, then absolutely open to it.

**Comment by sanajaved7** [comment]
@kjacks just created PR #918 as a potential simpler solution
