### ISSUE TITLE
Press releases error on production site

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#737]
This is what I see when I click on any press release on the production site.

[--- This issue is linked with an Asana task
#attachments [press release aerror.PNG](https://app.asana.com/app/asana/-/download_asset?asset_id=131018404884589), [blog post.PNG](https://app.asana.com/app/asana/-/download_asset?asset_id=131127671715216)
#url https://app.asana.com/0/0/131018404884583/f
---[aa]

**Comment by sanajaved7** [comment]
@kjacks this has been solved in staging right?

**Comment by rossvanderlinde** [comment]
I get the same error from blog posts too, it seems.

[--- Commented from Asana.com
#commenter Maria Elkin
---[aa]

**Comment by kjacks** [comment]
@sanajaved7 yep, it's solved in the staging branch
