### ISSUE TITLE
Policy paper attachments not downloading as PDFs

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#738]
Policy paper attachments don't appear to be working when you download them from the attachment box. It DLs an unrecognized file type. BUT, if i add ".pdf" to the end of the filename after I DL it, it opens fine.

[--- This issue is linked with an Asana task
#attachments [attachment.png](https://app.asana.com/app/asana/-/download_asset?asset_id=131019264177181), [Capture.PNG](https://app.asana.com/app/asana/-/download_asset?asset_id=131892769781477)
#url https://app.asana.com/0/0/131019264177175/f
---[aa]

**Comment by kjacks** [comment]
@mariaelkin I tried uploading pdfs, .xls, .doc, .txt and I haven't been seeing this error - let me know if you are still getting it!

**Comment by rossvanderlinde** [comment]
It might be a PC issue, because i've experienced it on both my work and my home computer with policy papers that were migrated...For example, when trying to download this policy paper: https://na-production.herokuapp.com/cybersecurity-initiative/policy-papers/the-graphic-guide-to-cybersecurity-and-simplicity/ <https://na-production.herokuapp.com/cybersecurity-initiative/policy-papers/the-graphic-guide-to-cybersecurity-and-simplicity/>

​
downloading it by clicking on the attachment gets me the file on the left--an unrecognized filetype. Copying the paper URL into a separate window lets me download an actual PDF. If I add .PDF to the file on the left, though, it opens normally.

Maybe we need to test this with non-Mac users?

- ME

[--- Commented from Asana.com
#commenter Maria Elkin
---[aa]

**Comment by rossvanderlinde** [comment]
@mariaelkin is this still a problem? if not let's close this in github

**Comment by mariaelkin** [comment]
It's still a problem, but we're going back in time to manually re-download
and re-upload the papers, so I guess we can close it

On Wed, May 18, 2016 at 12:06 PM, rossvanderlinde <notifications@github.com>
wrote:

> @mariaelkin <https://github.com/mariaelkin> is this still a problem? if
> not let's close this in github
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newamericafoundation/newamerica-cms/issues/738#issuecomment-220075936>
>



-- 

Maria Elkin

Communications Associate

New America

740 15th Street NW, Suite 900, Washington DC, 20005
Office  *(202) 986-2700*  |  *Direct **(202) 847-4769*  |  Email
elkin@newamerica.org  |  Twitter  @mvelkin <http://www.twitter.com/mvelkin>

**Comment by sanajaved7** [comment]
This should be resolved. Closing.
