### ISSUE TITLE
"Program Staff" not in Our People sidebar

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#744]
Should there be an option for program staff in the Our People sidebar?

[--- This issue is linked with an Asana task
#attachments [Screen Shot 2016-05-09 at 12.39.39 PM.png](https://app.asana.com/app/asana/-/download_asset?asset_id=131043860396213)
#url https://app.asana.com/0/0/131043860396210/f
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde would that page be a specific program's people page?

**Comment by rossvanderlinde** [comment]
I didn't create this issue -- @mariaelkin did you?

**Comment by kjacks** [comment]
@rossvanderlinde I think that Joanne created it, but because of the way the github sync is set up it shows up as you no matter who adds the issue.

Should I close this one then?
