### ISSUE TITLE
Finalize Order of Org Wide About Dropdown

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#755]

**Comment by rossvanderlinde** [comment]
Our Story, Our People, Funders, Press, Jobs
@mariaelkin do you agree?
Also need to check with Lauren M - I think we agreed on 'Funders' but it may have been 'Our Funders'

**Comment by mariaelkin** [comment]
I think that makes sense. Our Funders sounds better to me.

On Tue, May 10, 2016 at 10:55 AM, rossvanderlinde <notifications@github.com>
wrote:

> Our Story, Our People, Funders, Press, Jobs
> @mariaelkin <https://github.com/mariaelkin> do you agree?
> Also need to check with Lauren M - I think we agreed on 'Funders' but it
> may have been 'Our Funders'
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/newamericafoundation/newamerica-cms/issues/755#issuecomment-218183551>
>



-- 

Maria Elkin

Communications Associate

New America

740 15th Street NW, Suite 900, Washington DC, 20005
Office  *(202) 986-2700*  |  *Direct **(202) 847-4769*  |  Email
elkin@newamerica.org  |  Twitter  @mvelkin <http://www.twitter.com/mvelkin>

**Comment by kjacks** [comment]
@rossvanderlinde great - let me know when the order is finalized and I will make the changes
