### ISSUE TITLE
Asset Building Articles didn't get migrated

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#759]
I don't think Asset Building News Week articles got migrated. Flagging it before someone on Assets does: https://www.newamerica.org/tags/asset-building-articles/ <https://www.newamerica.org/tags/asset-building-articles/>

I think it makes sense for them to be blog posts...most of the other articles here appear to already exist as Weekly articles in Wagtail, but there are a few exceptions, like this one <https://www.newamerica.org/asset-building/the-not-so-secret-reality-for-millions-of-americans/>.

**Comment by sanajaved7** [comment]
Hey @rossvanderlinde - that's right. We didn't run any article transfer scripts except for Weekly because we need custom scripts to sort through those other CSVs. On that second part though, are you saying duplicate weekly articles came over?

**Comment by rossvanderlinde** [comment]
I think this was @mariaelkin -- yeh I'm aware they're not over and we've discussed this subsequently, so closing
