### ISSUE TITLE
Resizing images after they've been placed into CMS

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#762]
from Maria: I added an image to a simple page, but when it placed it in, it came in at full size. Being able to resize and/or move images around in the CMS would be a helpful feature in the future.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/131722831128264)
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;131722831128270">image size.PNG</a>

**Comment by LomaxRx** [comment]
We can add an image width field to allow users to specify % for rich text block. but not for image block.
