### ISSUE TITLE
Search Results - Person Content Type Display Inconsistency

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#766]
![screen shot 2016-05-10 at 5 31 32 pm](https://cloud.githubusercontent.com/assets/6720200/15163220/22b28ab8-16d5-11e6-895b-64a4f3582f4a.png)

**Comment by rossvanderlinde** [comment]
Not sure what the fix was here (or what the issue was) but since it's done i'm closing @kjacks
