### ISSUE TITLE
Picture Grid - Resize Height Issue

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#767]
- if a picture grid entry has been moused over in desktop mode and then the screen is resized to mobile, it will have excess height.
- this problem only arises in that specific instance, and not when the page is loaded in mobile or tablet size, or the user hasn't moused over any entries and subsequently resized -> low priority

**Comment by LomaxRx** [comment]
does #1193 address this @kjacks ?

**Comment by LomaxRx** [comment]
unable to duplicate. I think #1193 resolves this.
