### ISSUE TITLE
Bold formatting of first paragraph 

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#777]
Received feedback from Tyler in NYC office that it's confusing the first paragraph is bolded by default when inside the editor that styling hasn't been applied. 

cc: @rossvanderlinde 

<img width="545" alt="screen shot 2016-05-11 at 11 16 33 am" src="https://cloud.githubusercontent.com/assets/7397798/15186142/e5536fb2-1769-11e6-896c-0b9baf14be7b.png">

**Comment by rossvanderlinde** [comment]
Happy to review this in future but I think this is the style we went with and should stick to for the time being

**Comment by sanajaved7** [comment]
Hey @rossvanderlinde - reopening just so that we remember to come back to this in June, July etc whenever makes sense.

**Comment by rossvanderlinde** [comment]
sorry didn't mean to close, just comment

**Comment by rossvanderlinde** [comment]
Can we remove the auto bold from the first paragraph -- too many people have complained about it or are confused. We can revisit after launch
