### ISSUE TITLE
Re-categorizing someone as former staff does not remove them from their program's 'Our People' page

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#780]
Looks like you have to delete their program affiliation as well. Not necessarily a big problem, but something to note for people moving forward

**Comment by kjacks** [comment]
@rossvanderlinde we can add conditional to the query that generates the program people results if that would make the workflow easier?

**Comment by kjacks** [comment]
@sanajaved7 thoughts on this?

**Comment by sanajaved7** [comment]
@kjacks I think it'd be easier to add a filter to the database query itself so I can add that (it's a minor addition). Feel free to assign this to me!

**Comment by rossvanderlinde** [comment]
@kjacks @sanajaved7 1) this wasn't me (one drawback of everything coming via Asana -- I'll ask the comms team in future to sign off their name at the end of their Asana post. 2) I think it's fine to leave as is -- we need to remove people's program affiliations if they are former staff
