### ISSUE TITLE
Education Policy Papers - Spaces in Paper URLs 

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#786]
- Lindsey came across a handful of Ed policy papers where the link to the paper as a pdf had spaces - leading to validation errors in the editor.  If someone manually changes these spaces to %20, it works fine
- could also look into a more programmatic way of handling

**Comment by sanajaved7** [comment]
@rossvanderlinde do you know if these spaces are the result of the clean-up or the transfer script? It might make sense to handle this via a new transfer script.

**Comment by rossvanderlinde** [comment]
We're working our way through policy papers fixing paper links manually
