### ISSUE TITLE
URLs for Program Dropdown (location based progs that are hard coded)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#799]
Remove Chicago for the time being, and change DC link from /district to /dc

**Comment by rossvanderlinde** [comment]
Also in the longer term we can auto generate these

**Comment by kjacks** [comment]
@rossvanderlinde I believe that we chose to hard code them for now to get around the ordering problem, but could definitely look into generating dynamically in the future
