### ISSUE TITLE
Need to replace text on this page

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#826]
https://na-production.herokuapp.com/our-people/

Our experts are really great and have a lot of expertise in many different areas
And This is some text

**Comment by kjacks** [comment]
@rossvanderlinde Absolutely - let me know what the text should be

**Comment by rossvanderlinde** [comment]
@kjacks please can we go with:

"Our Board of Directors and Leadership Team provide strategic direction to the organization:"

And

"Find out more about our distinctive community of thinkers, writers, researchers, technologists, and community activists:"

That first one could be improved. @mariaelkin may have suggestions.

This really needs to be fixed and redeployed as a high priority -- the current text reads silly things like "our experts are really great" and "This is some text"
