### ISSUE TITLE
Some Initiatives need to be listed on the "Our People" page as well

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/newamerica-cms#827]
Rebecca Mackinnon would like "Ranking Digital Rights" to be listed on the "Our People" page as a program:
https://na-production.herokuapp.com/our-people/

![screen shot 2016-05-15 at 6 19 31 pm](https://cloud.githubusercontent.com/assets/941210/15277154/9b6ad90e-1ac9-11e6-9b2b-cfeed374a1cc.png)

cc @sloane101 @rossvanderlinde

**Comment by rossvanderlinde** [comment]
@georgiamoon that is a programs list. We can't start adding initiatives to it -- otherwise 10 other initiatives will ask for the same thing

**Comment by georgiamoon** [comment]
I'll let you and @FuzzHogan take that up with Rebecca.

**Comment by rossvanderlinde** [comment]
Sure -- feel free to send her our way. Unless leadership decides RDR is a program they won't appear in program lists but we can potentially add initiatives to this page at a later point.

**Comment by rossvanderlinde** [comment]
Will check with leadership

**Comment by LomaxRx** [comment]
can add initiative section with #1043 update

**Comment by LomaxRx** [comment]
will be resolved with #1043
