### ISSUE TITLE
Unpublished stories still show up in events content grid (and possibly elsewhere)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#830]
From Tyler B: 
I published an event -- A Conversation with David H. Petraeus -- and then unpublished it, but even after I do, it still shows up in the events tab listing:

https://na-production.herokuapp.com/events/?program_id=&date=%7B%22start%22%3A%222016-05-15%22%2C%22end%22%3A%222017-05-15%22%7D

**Comment by rossvanderlinde** [comment]
Same thing with unpublished initiatives showing up in the program dropdown.

**Comment by rossvanderlinde** [comment]
Just reopening because Kim Dancy reported that:

"I had placed a couple of pages in "draft" mode for now, but at least for me they seem to be showing up on the live site. Any way we can turn these off without deleting them entirely?"

I've asked for more info about where this is happening

**Comment by sanajaved7** [comment]
@rossvanderlinde I can't seem to replicate this issue on either staging and production with content types or programs - can she send a link of what's showing up?

**Comment by rossvanderlinde** [comment]
I think that events were showing up in the events content grid even after
being unpublished

Ross van der Linde

Director of Communications

New America

740 15th Street NW, Suite 900, Washington DC, 20005
Office  (202) 596-3602  |  Email vanderlinde@newamerica.org  |  Twitter
@rossvanderlinde <http://www.twitter.com/rossvanderlinde>

**Comment by sanajaved7** [comment]
@rossvanderlinde Just tested Education events and still working for me.
