### ISSUE TITLE
Content assigned to more than 1 program only showing up under 1 program in CMS

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#834]
Reported by Kevin at Open Markets:

Open Markets events arent showing up in the CMS under Open Markets events because they were assigned to another program as primary program. Can we change this so it works like initiative content appearing in both the initiative and program folder? Ideally an event assigned to Open Markets and New America NYC should appear in the CMS under the events pages in both programs' folders

I'm guessing this issue affects more than just events

**Comment by sanajaved7** [comment]
Discussed this in the meeting this morning. Closing issue.
