### ISSUE TITLE
Review Events page setup

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#837]
Multiple people have said they think past events are jumbled / not ordered. Actually they're ordered but start from exactly a year ago, which is too confusing.

One solution may be ordering past events (newest to oldest) differently from future events (oldest to newest). If someone selects dates that crossover both, then it can be ordered newest to oldest too.

A summer intern task could be assembling case studies of how other orgs handle events pages with past and future work. Should involve events team and Tyler B who flagged this issue

**Comment by rossvanderlinde** [comment]
Feedback from Assets:

It should be easier to access older event content. The only way to get back to events from more than one year ago is to click the "back one month" arrow button. This is acceptable for early 2015, it is monstrous for 2013 and entirely unmanageable for any period prior. Please add some functionality that allows for easier access to events from prior years.

**Comment by rossvanderlinde** [comment]
Will solicit feedback at next web stakeholder

**Comment by kjacks** [comment]
Feedback from meeting with Events team: 
- desire to keep separate future and past events pages with future events page as the default
- past events page ordered newest to oldest, future dates in datepicker disabled
- future events page ordered oldest to newest, past dates in datepicker disabled
