### ISSUE TITLE
Editor Content Block: Partner Organziation box

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#838]
For events..

Always added as just an image, which is untidy

**Comment by kjacks** [comment]
@rossvanderlinde not knowing too much about where this comes into play, this sounds like it might lend itself better to being a field in the event template?

**Comment by rossvanderlinde** [comment]
Only issue is there may be multiple partners. However you can create arrays
where multiple items are added with the plus icon, right?

**Comment by rossvanderlinde** [comment]
Tackled as part of the conference website template/model

**Comment by LomaxRx** [comment]
Will follow up with veronica to add this to the events template.
