### ISSUE TITLE
IE Word wrapping misbehaves

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#868]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/134185596215727)

**Comment by kjacks** [comment]
Resolved on Chrome, Firefox, Safari, Opera iOS Safari + Chrome, Android Chrome

Outstanding Issue on: Edge, I.E., Windows Phone Browsers

**Comment by kjacks** [comment]
This is an outstanding bug on IE and Edge where very long words will break certain layout components (e.g. the home page lead and featured stories blocks) due to lack of support for word-break, word-wrap, and hyphens css properties
