### ISSUE TITLE
Dropcap inconsistency

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#869]
![screen shot 2016-05-17 at 10 24 01 am](https://cloud.githubusercontent.com/assets/13524901/15325784/87473142-1c19-11e6-8d52-ff43cf9f3ae8.png)
Reported by Sade

**Comment by rossvanderlinde** [comment]
Doesn't appear to be different first paragraph lengths causing it

**Comment by kjacks** [comment]
@rossvanderlinde 

That post appears to have an empty p tag at the start, which will absolutely throw off the dropcap.  I've noticed this kind of strange formatting/extra empty tags on some of the other content that came over in the transfer too
![screen shot 2016-05-17 at 12 13 53 pm](https://cloud.githubusercontent.com/assets/6720200/15330066/342cb530-1c29-11e6-8598-96c5057399cc.png)
