### ISSUE TITLE
RSVP link in event shouldn't be compulsory

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#879]
Because a few events incl. the annual conference dont have public RSVPs
Also those without an RSVP should have the RSVP button hidden. Tagging @kjacks

**Comment by kjacks** [comment]
@rossvanderlinde Is this something we should still pursue, even though the rsvp buttons will no longer show up after the time has passed?

**Comment by georgiamoon** [comment]
Related: Follow up with Kirsten Holtz about alternatives to CVent links. She tried a google docs link and may have tried a "mailto:" link.
