### ISSUE TITLE
Research Topics (instead of Tags) Implementation

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#899]
![screen shot 2016-05-24 at 11 18 09 am](https://cloud.githubusercontent.com/assets/13524901/15509374/4c0a1fee-21a1-11e6-965c-87ded1c0ace2.png)
 possible approach

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/136703780855912)

**Comment by kjacks** [comment]
Essentially the idea here would be to replace the events carousel on program and subprogram home pages with a box highlighting topics that the program/subprogram focuses on.  These topics would correspond to the issue/topic pages that the program/subprogram had created.  Ideally program/subprogram content would be able to be tagged to one or multiple topics
