### ISSUE TITLE
RSVP link shouldn't show up after event has concluded

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#903]
Easiest solution may be that the RSVP button disappears on the day of the event, but that may be too early, especially for evening events. Not sure if we can use the 'time' field to be more precise, or just have an option to remove the RSVP button (there is also the issue of some events being full, others being invite-only etc not needign RSVP buttons)

Consult with veronica + events team

**Comment by kjacks** [comment]
Feedback from Events team: RSVP button should disappear at the date and time of the event, except if it is a multi-day event

Possible Solution: 
if (end date):
  disappear at end date
else:
  disappear at date + start time
