### ISSUE TITLE
Use "Page title" from promote panel for lead/feature blocks

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#912]
That way we can promote content with a more descriptive title like "Watch the Highlights: Basic Event Title" to the lead/feature blocks, while keeping "Basic Event Title" in content grids etc.

Obviously would default to the usual title field (in content tab) if the page title field (in promote tab) wasn't filled in

**Comment by georgiamoon** [comment]
- for lead stories, feature stories on home page, @rossvanderlinde will follow up with programs re program landing page
