### ISSUE TITLE
Weekly - Address Decline in Subscriptions

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#965]
Feedback from Emily Tamkin: 

The new website has made my life better in all ways but one, which is that "subscribers" for the Weekly is down by, like tens of tens. 

I do not know if there is an answer here, but something for consideration I thought I would flag.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/141021023754704)

**Comment by rossvanderlinde** [comment]
Suggestion: fixed strap across bottom of Weekly articles with sign up info

**Comment by rossvanderlinde** [comment]
![screen shot 2016-09-30 at 1 42 38 pm](https://cloud.githubusercontent.com/assets/13524901/19001111/d8d2e640-8713-11e6-8099-6463903cf4ce.png)
Pinging @tylerrichardett for his better version + possible ipad image

**Comment by tylerrichardett** [comment]
![ipad-weekly](https://cloud.githubusercontent.com/assets/17412375/19001815/1c11252c-8717-11e6-8fde-427db70074af.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-09-30 at 3 54 29 pm](https://cloud.githubusercontent.com/assets/13524901/19004962/480c5f3e-8726-11e6-8498-767c8fc43886.png)
How's this?
