### ISSUE TITLE
Review Blog Functionality

### ISSUE THREAD

**Issue by sanajaved7** [newamericafoundation/newamerica-cms#977]
Questions to answer:
- Should we be able to filter by initiative on program blog homepages? 
- Filter by date? 
- Should org wide blog homepage show blog posts or program blog homepages?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/141834492581033)

**Comment by sanajaved7** [comment]
Recap of discussion from web stakeholders meeting on 6/16:
- No way to currently find blog homepages from newamerica.org 
- On org wide blog homepage, no way to tell which posts are associated with which blog

A few possible approaches - solution could be a combination:  
1. Links to blogs on org homepage before "Our Story"
2. List of all blogs then all recent posts stream underneath 
3. Grid of blogs plus their most recent 2-3 posts 
4. Just a grid of the blogs 
5. Adding name and link to blog homepage on current grid

Next steps: @rossvanderlinde will draft a few designs to bring to next meeting to visualize some of the options above

**Comment by rossvanderlinde** [comment]
From Kirk: Currently the only way to get from an article back to its parent blog is to use the breadcrumbs, which don't appear on mobile/tablet, leaving users with no way of accessing other content within the blog
